var MAX_PLAY_LENGTH = 6;
var res = {
    agreementjson:"res/ui/Agreement.json",
    assertui:"res/ui/AssetMgr.json",
    chatui:"res/ui/ChatNew.json",
    //chatsl:"res/ui/ChatSaoLei.json",
    chatnys:"res/ui/ChatNYS.json",
    createroomjson0: "res/ui/CreateRoomWindow0.json",
    createroomjson1: "res/ui/CreateRoomWindow1.json",
    createroomjson2: "res/ui/CreateRoomWindow2.json",
    createroomjson3: "res/ui/CreateRoomWindow3.json",
    createroomjson4: "res/ui/CreateRoomWindow4.json",
    createroomjson5: "res/ui/CreateRoomWindow5.json",
    createroomjson6: "res/ui/CreateRoomWindow6.json",
    createroomjson7: "res/ui/CreateRoomWindow7.json",
    createroomjson8: "res/ui/CreateRoomWindow8.json",
    createroomjson9: "res/ui/CreateRoomWindow9.json",
    createroomjson10: "res/ui/CreateRoomWindow10.json",
    creatRoombaofang:"res/ui/CreatRoombaofang.json",
    creatRoombaofangnys:"res/ui/CreatRoombaofangnys.json",
    exitroom: "res/ui/ExitRoom.json",
    msexitroom: "res/ui/MineSweepingExit.json",
    jionroomui2: "res/ui/Invitecode.json",
  //  buycardui:"res/ui/IOSPayWindow.json",
    jionroomui: "res/ui/JoinRoomWindow.json",
    loginui_loginpngpjson: "res/ui/LoginMenu.json",
    mailjson:"res/ui/Mail.json",
    halluijson: "res/ui/MainWindow.json",
    hallGolduijson: "res/ui/goldScene.json",
    goldScwelcome: "res/ui/goldScwelcome.json",
    //goldCRPrevCenter1json: "res/ui/goldCRPrevCenter1.json",
    //goldCRPrevCenter2json: "res/ui/goldCRPrevCenter2.json",
    //goldCRPrevRightjson: "res/ui/goldCRPrevRight.json",
    //goldCRPrevTopjson: "res/ui/goldCRPrevTop.json",
    goldCRPrevType0json: "res/ui/goldCRPrevType0.json",
    goldCRPrevType1json: "res/ui/goldCRPrevType1.json",
    goldCreateRoomjson: "res/ui/goldCreateRoom.json",
    msgbox: "res/ui/MessageBox.json",
    btn_layerJson:"res/ui/btn_Layer.json",
    RecordBureau:"res/ui/RecordBureau.json",
    gameShareJson:"res/ui/shareLayer.json",
    RecordReplayList:"res/ui/RecordReplayList.json",
    //RecordReplayListCell:"res/ui/RecordReplayListCell.json",
    //RecordBureauCell:"res/ui/RecordBureauCell.json",
    setting: "res/ui/SettingWindow.json",
    //tuitongzitable:"res/ui/TuitongziTable.json",
    //goldtuitongzitable:"res/ui/goldTuitongziTable.json",
    //pintianjiutable:"res/ui/Pingtianjiu.json",
    //goldpintianjiutable:"res/ui/goldPingtianjiu.json",
    //pintianjiugroups:"res/ui/pingtianjiu/groups.json",
    //pintianjiugroups:"res/game/pingtianjiu/ptj_group.json",
    //pintianjiuoneresult:"res/ui/PTJEndPlayWindow.json",
    zjhtablefk:"res/ui/zjhtablefk.json",
    recordListCell:"res/ui/recordListCell.json",
    safeLayerJson:"res/ui/safeLayer.json",
    recordCell:"res/ui/recordCell.json",
    //Ttz_record:"res/ui/Ttz_record.json",
    //Ptj_record:"res/ui/Ptj_record.json",
    auditLayer:"res/ui/auditLayer.json",
    chatMicLayer:"res/ui/lookPlayerLayer.json",
    chatMicLayer_sl:"res/ui/lookPlayerLayer_sl.json",
    rankingList:"res/ui/rankingListLayer.json",
    rankingCell:"res/ui/rankingCell.json",
    rankingPlayerInfo:"res/ui/rankingInfo.json",
    personalSetLayer:"res/ui/personalSetLayer.json",
    goldShop:"res/ui/goldShop.json",
    goldNysTable:"res/ui/goldNysTable.json",
    leopardKingTable:"res/ui/leopardKing.json",
   // dragonTable:"res/ui/Dragon.json",
    goldFishTable:"res/ui/goldfish.json",
    dxtbTable:"res/ui/dafuhao.json",
   // goldYybf:"res/ui/goldyybf.json",
    longhudou:"res/ui/longhudou.json",
    goldRacing:"res/ui/goldRacing.json",
    //goldYsz:"res/ui/goldYszTable.json",
    //yszSZ:"res/ui/yszSZ.json",
    //yszWz:"res/ui/yszWz.json",
    //yszRecord:"res/ui/yszRecord.json",
    lhdRecord:"res/ui/lhdRecord.json",
    lhdRecordCell:"res/ui/lhdRecordCell.json",
    //yybfRecord:"res/ui/yybfRecord.json",
    //yybfRecordCell:"res/ui/yybfRecordCell.json",
    //yybfRank:"res/ui/yybfRank.json",
    //yybfRankCell:"res/ui/yybfRankCell.json",
    //yybfBetsCell:"res/ui/yybfBetsCell.json",
    zhaomu:"res/ui/zhaomu.json",
    //bzwRecord:"res/ui/bzwRecord.json",
    //bzwRecordCell:"res/ui/bzwReacodCell.json",
    //bzwSZ:"res/ui/bzwSZ.json",
    //bzwSZcell:"res/ui/bzwSZcell.json",
    bzwWz:"res/ui/bzwWz.json",
    bzwWzCell:"res/ui/bzwWuzuoCell.json",
    report:"res/ui/reportLayer.json",
    bank:"res/ui/bank.json",
    goldzhanjicell:"res/ui/goldzhanjicell.json",
    erbagangTable:"res/ui/A_erbagang.json",
    ebgRecord:"res/ui/A_ebgRecord.json",
    pdkTable:"res/ui/A_pdkTable.json",
    //sxdbTable:"res/ui/A_sxdbTable.json",
    //sxdbRecord:"res/ui/sxdbRecord.json",
    //fpjTable:"res/ui/gold_fpj.json",
    //fpjDouble:"res/ui/gold_fpjdouble.json",
    //fpjHelp:"res/ui/gold_help.json",
    //fpjWin:"res/ui/gold_fpjwin.json",
    pdktableFk:"res/ui/PdkTable.json",
    pdkresultui:"res/ui/PdkEndWindow.json",
    pdkresultoneui:"res/ui/PdkEndPlayWindow.json",

    loadingJson:"res/roomAnimate/loading.json",
    loadingAtlas:"res/roomAnimate/loading.atlas",
    loadingPng:"res/roomAnimate/loading.png",

    wanfaImg0:"res/niuniuRes/wanfaImg0.png",
    wanfaImg1:"res/niuniuRes/wanfaImg1.png",
    wanfaImg2:"res/niuniuRes/wanfaImg2.png",
    wanfaImg3:"res/niuniuRes/wanfaImg3.png",
    wanfaImg4:"res/niuniuRes/wanfaImg4.png",
    wanfaImg5:"res/niuniuRes/wanfaImg5.png",
    wanfaImg6:"res/niuniuRes/wanfaImg6.png",
    wanfaImg7:"res/niuniuRes/wanfaImg7.png",
    wanfaImg8:"res/niuniuRes/wanfaImg8.png",
    wanfaImg9:"res/niuniuRes/wanfaImg9.png",

    jxnntable: "res/ui/jxnnTable.json",
    nysresultui:"res/ui/nysEndPlayWindow.json",
    nystable: "res/ui/NysTable.json",
    niuniuRoomHelpJson:"res/ui/roomHelpBtnLayer.json",
    ninniutable: "res/ui/NiuniuTable.json",
    zjhtable: "res/ui/ZjhTable.json",
    ddzhutable: "res/ui/DdzhuTable.json",
    zjhresultoneui: "res/ui/ZjhEndPlayWindow.json",
    resultoneui: "res/ui/EndPlayWindow.json",
    resultui:"res/ui/EndWindow.json",

    login_animate_json:"res/logo.json",
    login_animate_png:"res/logo.png",
    login_animate_atlas:"res/logo.atlas",

    hall_animate_json:"res/hall.json",
    hall_animate_png:"res/hall.png",
    hall_animate_atlas:"res/hall.atlas",

    ddzhuresultoneui: "res/ui/DdzEndPlayWindow.json",
    //sdbtable:"res/ui/sdbTable.json",
    //sdbEndPlayWindow:"res/ui/SdbEndPlayWindow.json",
    //sdbEndWindow:"res/ui/SdbEndWindow.json",
    zjhresultui:"res/ui/ZjhEndWindow.json",
    ddzhuresultui:"res/ui/DdzEndWindow.json",

    ddzRecordjson:"res/ui/DdzRecord.json",
    nnRecordjson:"res/ui/NiuNiu_record.json",

    //minesweeping:"res/ui/SaoLeiTable.json",
    //minesweepingbg:"res/ui/SaoLeiBg.json",
    //minesweepingresult2:"res/ui/SaoLeiResult2.json",
    //minesweepingresult:"res/ui/SaoLeiResult.json",
    minesweepingmsg:"res/ui/MessageBoxP.json",
  //  minesweepingdialog:"res/ui/SaoLeiDialog.json",
    minesweepingmenu:"res/ui/MineSweeping_Menu.json",
    minesweepingrule:"res/ui/MineSweepingRule.json",
    cuoPaiLayer:"res/ui/cuoPaiLayer.json",

    tips_bg:"res/niuniu/img_tips_bg.png",
    //动画
    cardsBigplist1: "res/large_poker1.plist",
    cardsBigplist2: "res/large_poker2.plist",
    cardsBigplist3: "res/large_poker3.plist",
    cardsplist: "res/cards.plist",
    cardspng: "res/cards.png",
    ani1list: "res/ani1.plist",
    ani1png: "res/ani1.png",
    niuniuCountPlist:"res/niuniuRes/niuniuCount.plist",
    niuniuCountPng:"res/niuniuRes/niuniuCount.png",
    goldniuniuCountPlist:"res/niuniuRes/goldniuniu.plist",
    goldniuniuCountPng:"res/niuniuRes/goldniuniu.png",
    img_buqiang:"res/niuniuRes/img_buqiang@2x.png",
    img_qiangzhuang:"res/niuniuRes/img_qiangzhuang@2x.png",
    btn_meiniu:"res/niuniuRes/331_btn_meiniu@2x.png",
    btn_youniu:"res/niuniuRes/331_btn_youniu@2x.png",
    btn_dizhu:"res/niuniuRes/btn_dizhu@2x.png",
    //ddzWinBg:"res/niuniuRes/jiassuan_bg1@2x.png",
    ddzLostBg:"res/niuniuRes/jiesuan_bg2@2x.png",
    btn_nongmin:"res/niuniuRes/btn_nongmin@2x.png",
    //斗地主资源图片一般放这里
    bombplist: "res/niuniuRes/anim/bomb.plist",
    bombpng: "res/niuniuRes/anim/bomb.png",
    feijiplist: "res/niuniuRes/anim/feiji.plist",
    feijipng: "res/niuniuRes/anim/feiji.png",
    shunzplist: "res/niuniuRes/anim/shunz.plist",
    shunzpng: "res/niuniuRes/anim/shunz.png",
    lianduilist: "res/niuniuRes/anim/liandui.plist",
    lianduipng: "res/niuniuRes/anim/liandui.png",
    wangzhaplist: "res/niuniuRes/anim/wang_zha.plist",
    wangzhappng: "res/niuniuRes/anim/wang_zha.png",

    spring0plist: "res/niuniuRes/anim/spring0.plist",
    spring0png: "res/niuniuRes/anim/spring0.png",
    alarmplist: "res/niuniuRes/anim/alarm.plist",
    alarmpng: "res/niuniuRes/anim/alarm.png",

    spr_double2:"res/niuniuRes/bei@2x.png",
    spr_double1:"res/niuniuRes/bei@1x.png",
    img_input:"res/niuniuRes/img_input@2x.png",
    img_laizi_bg:"res/niuniuRes/img_laiz2i@2x.png",
    rogue:"res/niuniuRes/roguetag.png",
    zhanji_bg:"res/niuniuRes/zhanji_bg3@2x.png",
    bureau_bg:"res/niuniuRes/bg5@2x.png",
    img_jiaobiao:"res/niuniuRes/img_jiaobiao@2x.png",
    ddzCall0:"res/niuniuRes/call0.png",
    ddzCall1:"res/niuniuRes/call1.png",
    ddzCall2:"res/niuniuRes/call2.png",
    ddzCall3:"res/niuniuRes/call3.png",

    sdb_endBomb:"res/niuniuRes/bomb@2x.png",
    sdb_endGaoPai:"res/niuniuRes/img_gaopai@2x.png",
    sdb_endShiDianBan:"res/niuniuRes/img_shidianban@2x.png",
    sdb_endWuXiao:"res/niuniuRes/img_wuxiao@2x.png",
    sdb_endHuaWuXiao:"res/niuniuRes/img_huawuxiao-@2x.png",
    sdb_endTianWang:"res/niuniuRes/img_tianwang@2x.png",

    showcallScore02:"res/niuniuRes/showcallScore02.png",
    btn_quqian:"res/ui/commonCells/commonPic/inRoomSamePic/btn_quqian@2x.png",

    //ttz
    tousaizi_skeleton:"res/game/tuitongzi/animate/skeleton.atlas",
    tousaizi_json:"res/game/tuitongzi/animate/skeleton.json",
    tousaizi_png:"res/game/tuitongzi/animate/skeleton.png",
    touziplist: "res/game/tuitongzi/ui/touzi.plist",
    touzipng: "res/game/tuitongzi/ui/touzi.png",
    //动画
    //ptjsaizijson:"res/game/pingtianjiu/animate/touzhong.json",
    //ptjsaiziatlas:"res/game/pingtianjiu/animate/touzhong_tex.atlas",
    //ptjsaizipng:"res/game/pingtianjiu/animate/touzhong_tex.png",

    //dileiJ:"res/roomAnimate/dilei.json",
    //dileiA:"res/roomAnimate/dilei.atlas",
    //dileiP:"res/roomAnimate/dilei.png",
    //dileiP1:"res/roomAnimate/dilei2.png",

    //dilei2J:"res/roomAnimate/dilei22.json",
    //dilei2A:"res/roomAnimate/dilei22.atlas",
    //dilei2P:"res/roomAnimate/dilei22.png",

    //btnAnimatejson0:"res/btnAnimate/pintianjiu.json",
    //btnAnimateatlas0:"res/btnAnimate/pintianjiu.atlas",
    //btnAnimatepng0:"res/btnAnimate/pintianjiu.png",
    //
    //btnAnimatejson1:"res/btnAnimate/pinsanzhang.json",
    //btnAnimateatlas1:"res/btnAnimate/pinsanzhang.atlas",
    //btnAnimatepng1:"res/btnAnimate/pinsanzhang.png",

    btnAnimatejson2:"res/btnAnimate/niuniu.json",
    btnAnimateatlas2:"res/btnAnimate/niuniu.atlas",
    btnAnimatepng2:"res/btnAnimate/niuniu.png",

    btnAnimatejson3:"res/btnAnimate/doudizhu.json",
    btnAnimateatlas3:"res/btnAnimate/doudizhu.atlas",
    btnAnimatepng3:"res/btnAnimate/doudizhu.png",

    btnAnimatejson4:"res/btnAnimate/paodekuai.json",
    btnAnimateatlas4:"res/btnAnimate/paodekuai.atlas",
    btnAnimatepng4:"res/btnAnimate/paodekuai.png",

    //btnAnimatejson5:"res/btnAnimate/shidianban.json",
    //btnAnimateatlas5:"res/btnAnimate/shidianban.atlas",
    //btnAnimatepng5:"res/btnAnimate/shidianban.png",
    //
    //btnAnimatejson6:"res/btnAnimate/tuitongzi.json",
    //btnAnimateatlas6:"res/btnAnimate/tuitongzi.atlas",
    //btnAnimatepng6:"res/btnAnimate/tuitongzi.png",

    //btnAnimatejson7:"res/btnAnimate/saolei.json",
    //btnAnimateatlas7:"res/btnAnimate/saolei.atlas",
    //btnAnimatepng7:"res/btnAnimate/saolei.png",

    btnAnimatejson8:"res/btnAnimate/niuyuanshuai.json",
    btnAnimateatlas8:"res/btnAnimate/niuyuanshuai.atlas",
    btnAnimatepng8:"res/btnAnimate/niuyuanshuai.png",

    grilAnimatejson:"res/roomAnimate/beauty.json",
    grilAnimateatlas:"res/roomAnimate/beauty.atlas",
    grilAnimatepng:"res/roomAnimate/beauty.png",

    createAnimatejson:"res/roomAnimate/chuangjianfangjian.json",
    createAnimateatlas:"res/roomAnimate/chuangjianfangjian.atlas",
    createAnimatepng:"res/roomAnimate/chuangjianfangjian.png",

    joinAnimatejson:"res/roomAnimate/jiarufangjian.json",
    joinAnimateatlas:"res/roomAnimate/jiarufangjian.atlas",
    joinAnimatepng:"res/roomAnimate/jiarufangjian.png",

    touchAnimatejson:"res/roomAnimate/shubiaodianji.json",
    touchAnimateatlas:"res/roomAnimate/shubiaodianji.atlas",
    touchAnimatepng:"res/roomAnimate/shubiaodianji.png",

    xinpinAnimatejson:"res/roomAnimate/xinpin.json",
    xinpinAnimateatlas:"res/roomAnimate/xinpin.atlas",
    xinpinAnimatepng:"res/roomAnimate/xinpin.png",

    jinbichangAnimatejson:"res/roomAnimate/jinbichang.json",
    jinbichangAnimateatlas:"res/roomAnimate/jinbichang.atlas",
    jinbichangAnimatepng:"res/roomAnimate/jinbichang.png",

    fangkachangAnimatejson:"res/roomAnimate/fangkachang.json",
    fangkachangAnimateatlas:"res/roomAnimate/fangkachang.atlas",
    fangkachangAnimatepng:"res/roomAnimate/fangkachang.png",

    julebuAnimatejson:"res/roomAnimate/julebu.json",
    julebuAnimateatlas:"res/roomAnimate/julebu.atlas",
    julebuAnimatepng:"res/roomAnimate/julebu.png",

    shangchengAnimatejson:"res/roomAnimate/shangcheng.json",
    shangchengAnimateatlas:"res/roomAnimate/shangcheng.atlas",
    shangchengAnimatepng:"res/roomAnimate/shangcheng.png",

    ttz_bg_frontcard:"res/ui/tuitongzi/ttz_bg_frontcard.png",
    ttz_bg_backcard:"res/ui/tuitongzi/ttz_bg_backcard.png",

    ttz_card_11:"res/game/tuitongzi/ui/ttz_card_11.png",
    ttz_card_12:"res/game/tuitongzi/ui/ttz_card_12.png",
    ttz_card_13:"res/game/tuitongzi/ui/ttz_card_13.png",
    ttz_card_14:"res/game/tuitongzi/ui/ttz_card_14.png",
    ttz_card_15:"res/game/tuitongzi/ui/ttz_card_15.png",
    ttz_card_16:"res/game/tuitongzi/ui/ttz_card_16.png",
    ttz_card_17:"res/game/tuitongzi/ui/ttz_card_17.png",
    ttz_card_18:"res/game/tuitongzi/ui/ttz_card_18.png",
    ttz_card_19:"res/game/tuitongzi/ui/ttz_card_19.png",
    ttz_card_37:"res/game/tuitongzi/ui/ttz_card_37.png",
    ttz_stzz:"res/game/tuitongzi/ui/ttz_stzz.png",
    ttz_baozi:"res/game/tuitongzi/ui/ttz_baozi.png",
    ttz_ebg:"res/game/tuitongzi/ui/ttz_ebg.png",
    ttz_nod:"res/game/tuitongzi/ui/ttz_nod.png",
    ttz_img95:"res/game/tuitongzi/ui/ttz_jiudb.png",
    ttz_img90:"res/game/tuitongzi/ui/ttz_jiud.png",
    ttz_img80:"res/game/tuitongzi/ui/ttz_bad.png",
    ttz_img85:"res/game/tuitongzi/ui/ttz_badb.png",
    ttz_img70:"res/game/tuitongzi/ui/ttz_qid.png",
    ttz_img75:"res/game/tuitongzi/ui/ttz_qidb.png",
    ttz_img65:"res/game/tuitongzi/ui/ttz_liudb.png",
    ttz_img60:"res/game/tuitongzi/ui/ttz_liud.png",
    ttz_img50:"res/game/tuitongzi/ui/ttz_wud.png",
    ttz_img55:"res/game/tuitongzi/ui/ttz_wudb.png",
    ttz_img40:"res/game/tuitongzi/ui/ttz_sid.png",
    ttz_img45:"res/game/tuitongzi/ui/ttz_sidb.png",
    ttz_img35:"res/game/tuitongzi/ui/ttz_sandb.png",
    ttz_img30:"res/game/tuitongzi/ui/ttz_sand.png",
    ttz_img20:"res/game/tuitongzi/ui/ttz_erd.png",
    ttz_img25:"res/game/tuitongzi/ui/ttz_erdb.png",
    ttz_img10:"res/game/tuitongzi/ui/ttz_yid.png",
    ttz_img15:"res/game/tuitongzi/ui/ttz_yidb.png",
    ttz_tongsha:"res/game/tuitongzi/ui/ttz_tongsha.png",
    ttz_tongpei:"res/game/tuitongzi/ui/ttz_tongpei.png",

   ttz_kaipai:"res/ui/tuitongzi/ttz_img_kaipai.png",
    // ttz_bets3:"res/ui/tuitongzi/ttz_img_3fen.png",
    // ttz_bets5:"res/ui/tuitongzi/ttz_img_5fen.png",
    // ttz_bets7:"res/ui/tuitongzi/ttz_img_7fen.png",

    //拼天九
    //ptj_painumplist:"res/game/pingtianjiu/ui/ptj_painum.plist",
    //ptj_painumpng:"res/game/pingtianjiu/ui/ptj_painum.png",
    //ptj_cardshubg:"res/ui/pingtianjiu/ptj_img_back1@2x.png",
    //ptj_cardhengbg:"res/ui/pingtianjiu/ptj_img_back2@2x.png",
    //
    //ptj_Atlasjia:"res/ui/pingtianjiu/ptj_jia@2x.png",
    //
    //ptj_Atlasjian:"res/game/pingtianjiu/ui/ptj_jian@2x.png",
    //ptj_losebg:"res/game/pingtianjiu/ui/ptj_bg_lose@2x.png",
    //ptj_losetitle:"res/game/pingtianjiu/ui/ptj_title_lose@2x.png",
    //
    //ptj_Atlasfont1:"res/ui/pingtianjiu/ptj_font1.png",
    //ptj_Atlasfont2:"res/ui/pingtianjiu/ptj_font2.png",
    //ptj_img_he:"res/ui/pingtianjiu/ptj_img_he@2x.png",
    //ptj_img_lose:"res/ui/pingtianjiu/ptj_img_lose@2x.png",
    //ptj_img_win:"res/ui/pingtianjiu/ptj_img_win@2x.png",

    //newRes
    //zjhfen5: "res/niuniuRes/p1@2x.png",
    //nn331_beimian:"res/ui/inRoomSamePic/yypk_img_pokerBack2@2x.png",
    //pokercard:"res/niuniuRes/pokercard1.png",
    winlogo:"res/ui/zjhCells/zjhPic/bipai/psz_img_win@2x.png",

    loselogo:"res/game/zjh/ui/psz_img_lose@2x.png",

    pokerBei:"res/commonUi/yypk_img_pokerBack2@2x.png",
    img1:"res/niuniuRes/yypk_imh_1fen.png",
    img2:"res/niuniuRes/yypk_imh_2fen.png",
    img3:"res/niuniuRes/yypk_imh_3fen.png",
    img4:"res/niuniuRes/yypk_imh_4fen.png",
    img5:"res/niuniuRes/yypk_imh_5fen.png",
    img6:"res/niuniuRes/yypk_imh_6fen.png",
    img7:"res/niuniuRes/yypk_imh_7fen.png",
    img8:"res/niuniuRes/yypk_imh_8fen.png",
    img9:"res/niuniuRes/yypk_imh_9fen.png",
    img10:"res/niuniuRes/yypk_img_10fen.png",
    chip1:"res/game/zjh/ui/chip1.png",
    chip2:"res/game/zjh/ui/chip2.png",
    chip3:"res/game/zjh/ui/chip3.png",
    chip4:"res/game/zjh/ui/chip4.png",
    chip5:"res/game/zjh/ui/chip5.png",
    chip6:"res/game/zjh/ui/chip6.png",
    chip8:"res/game/zjh/ui/chip8.png",
    chip10:"res/game/zjh/ui/chip10.png",
    chip50:"res/game/zjh/ui/chip50.png",
    chip100:"res/game/zjh/ui/chip100.png",
    chip200:"res/game/zjh/ui/chip200.png",
    chip500:"res/game/zjh/ui/chip500.png",
    chip1000:"res/game/zjh/ui/chip1000.png",
    chip2000:"res/game/zjh/ui/chip2000.png",
    chip5000:"res/game/zjh/ui/chip5000.png",
    chip10000:"res/game/zjh/ui/chip10000.png",

    kanpaiLogo: "res/game/zjh/ui/psz_img_kanpai@2x.png",
    qipaiLogo:"res/game/zjh/ui/psz_img_qipai@2x.png",
    zjhprogress:"res/game/zjh/ui/pt0.png",

    voiceJson:"res/commonAnim/voice.json",
    voiceAtlas:"res/commonAnim/voice.atlas",
    voicePng:"res/commonAnim/voice.png",

    chatbg_ld: "res/commonUi/room/chat_left@2x.png",
    chatbg_rd: "res/commonUi/room/chat_right@2x.png",
    chatbg_ud:"res/commonUi/room/chat_up@2x.png",
    chatbg_ud1:"res/commonUi/room/chat_up1@2x.png",
    progressBar:"res/commonUi/room/yypk_img_timing@2x.png",
    soundopen0: "res/commonUi/room/yypk_img_horn1@2x@2x.png",
    soundopen1:"res/commonUi/room/yypk_img_horn2@2x@2x.png",
    soundopen2:"res/commonUi/room/yypk_img_horn3@2x@2x.png",

    text_saolei:"res/game/saolei/ui/sl_img_saolei@2x.png",
    progress_saolei:"res/game/saolei/ui/ptj_img_jishi@2x.png",
    coin_saolei:"res/game/saolei/ui/yyl_img_gold@2x.png",
    btn_ready:"res/ui/commonCells/commonPic/inRoomSamePic/yypk_btn_ready@2x.png",

    btn_zanting:"res/commonUi/record/hf_btn_stop@2x.png",
    btn_bofang:"res/ui/commonCells/commonPic/recordPic/hf_btn_play@2x.png",

    //pageOne:"res/ui/buyCard/1.png",

    pageTwo:"res/commonUi/buyCard/2.png",
    pageThree:"res/commonUi/buyCard/3.png",
    pageFour:"res/commonUi/buyCard/4.png",

    //unselectDian:"res/ui/buyCard/jy_suolueqiu1.png",
    //selectDian:"res/ui/buyCard/jy_suolueqiu2.png",

    blueSafe:"res/ui/safeLayer/yypk_img_bluews@2x.png",
    redSafe:"res/commonUi/safeLayer/yypk_img_redws@2x.png",

    guangxiao_json: "res/btnAnimate/light/guangxiao.json",
    guangxiao_atlas: "res/btnAnimate/light/guangxiao.atlas",
    guangxiao_png: "res/btnAnimate/light/guangxiao.png",

    maskLayer:"res/maskLayer.png",
    nn331_beimian_big:"res/nn331_beimian_big.png",
    //nn331_beimian:"res/nn331_beimian.png",
    tuoGuang_0:"res/ui/niuniuPic/btn_tuoguan1.png",
    tuoGuang_1:"res/niuniu/btn_tuoguan2.png",


    random_zhuangPng1:"res/niuniu/randomZhuang1.png",
    random_zhuangPng2:"res/niuniu/randomZhuang2.png",
    btn_samllblue:"res/niuniu/btn_samllblue@2x.png",
    btn_smallgreen:"res/niuniu/btn_smallgreen@2x.png",
    select_zhuangPng:"res/game/nys/ui/desktop_player_bg_box4@2x.png",
    img_qiangZhuang0:"res/niuniu/img_bei0@2x.png",
    img_qiangZhuang1:"res/niuniu/img_bei1@2x.png",
    img_qiangZhuang2:"res/niuniu/img_bei2@2x.png",
    img_qiangZhuang3:"res/niuniu/img_bei3@2x.png",
    img_qiangZhuang4:"res/niuniu/img_bei4@2x.png",
    niuniuAnimateGold:"res/niuniu/img_gold@2x.png",
    //cuoPaiOneLayer:"res/ui/cuoPaiOneLayer.json",
    chatMicLayer:"res/ui/lookPlayerLayer.json",
	
	 //---------------------------俱乐部--------------------------
    julebu_infolist:"res/ui/Clubinfomyself.json",
    julebu_clubmanger:"res/ui/Clubmanger.json",
    julebu_clubpersons:"res/ui/ClubPersons.json",
    julebu_clubcells:"res/ui/Clubcells.json",
    julebu_rankItem:"res/ui/clubRankItem.json",
    julebu_recordUser:"res/ui/clubRecordUser.json",
    julebu_recordItem:"res/ui/clubRecordItem.json",
    julebu_roomListItem:"res/ui/clubRoomListItem.json",
    julebu_roomSetItem:"res/ui/clubRoomSetItem.json",
    julebu_applyListItem:"res/ui/clubApplyListItem.json",
    julebu_dynamic:"res/ui/clubDynamic.json",
    julebu_statistics:"res/ui/clubStatistics.json",
    julebu_memberItem:"res/ui/clubMemberItem.json",

    //julebuAnimatejson:"res/roomAnimate/julebu.json",
    //julebuAnimateatlas:"res/roomAnimate/julebu.atlas",
    //julebuAnimatepng:"res/roomAnimate/julebu.png",

    selectbg1:"res/ui/commonCells/commonPic/createPic/yypk_btn_unselect@2x.png",
    selectgou1:"res/ui/commonCells/commonPic/createPic/yypk_btn_select@2x.png",
    headbgkuang:"res/ui/clubres/clubinfo/club_bg_player1.png",
    julebucellbg:"res/ui/clubres/clubinfo/club_bg_infor@2x.png",

    julebu_sqjr:"res/commonUi/club/club_btn_sqjr@2x.png",
    julebu_yisqjr:"res/commonUi/club/club_btn_qxsq@2x.png",
    julebu_yijiesan:"res/commonUi/club/club_img_already@2x.png",
    julebu_kfcellbg:"res/commonUi/club/club_bg_xxtz@2x.png",
    julebu_kfbtn:"res/commonUi/club/club_btn_kf@2x.png",

    jublebu_1:"res/commonUi/club/jy_jxnn.png",
    jublebu_2:"res/commonUi/club/jy_kwx.png",
    jublebu_7:"res/commonUi/club/jy_psz.png",
    jublebu_16:"res/commonUi/club/jy_jxnn.png",
    jublebu_6:"res/commonUi/club/jy_ddz.png",
    jublebu_65:"res/commonUi/club/jy_nys.png",
    jublebu_19:"res/commonUi/club/jy_ptj.png",
    jublebu_17:"res/commonUi/club/jy_ttz.png",
    jublebu_10:"res/commonUi/club/jy_sdb.png",
    jublebu_x1:"res/commonUi/club/jy_pdk.png",
    jublebu_36:"res/commonUi/club/jy_saolei.png",

    jublebu_joinroombtn:"res/commonUi/club/club_btn_joinroom@2x.png",
    jublebu_setkfbtn:"res/commonUi/club/club_btn_shezhi@2x.png",
    jublebu_agreejoin:"res/commonUi/club/yypk_btn_agree@2x.png",
    jublebu_refusejoin:"res/commonUi/club/yypk_btn_refuse@2x.png",
    //俱乐部改版
    clubIcon0:"res/ui/clubres/clubinfo/club_icon1@2x.png",
    clubIcon1:"res/ui/clubres/clubinfo/club_icon2@2x.png",
    clubIcon2:"res/ui/clubres/clubinfo/club_icon3@2x.png",
    clubIcon3:"res/ui/clubres/clubinfo/club_icon4@2x.png",


    //卡五星
    //干掉蛋疼的特效动画
    //mjpeng_txatlas: "res/ui/kwxResource/newkwxres/animations/peng_tx.atlas",
    //mjpeng_txjson: "res/ui/kwxResource/newkwxres/animations/peng_tx.json",
    //mjpeng_txpng: "res/ui/kwxResource/newkwxres/animations/peng_tx.png",
    //mjangang_txatlas: "res/ui/kwxResource/newkwxres/animations/angang_tx.atlas",
    //mjangang_txjson: "res/ui/kwxResource/newkwxres/animations/angang_tx.json",
    //mjangang_txpng: "res/ui/kwxResource/newkwxres/animations/angang_tx.png",
    //mjmingang_txatlas: "res/ui/kwxResource/newkwxres/animations/minggang_tx.atlas",
    //mjmingang_txjson: "res/ui/kwxResource/newkwxres/animations/minggang_tx.json",
    //mjmingang_txpng: "res/ui/kwxResource/newkwxres/animations/minggang_tx.png",
    //mjgangskh_txatlas: "res/ui/kwxResource/newkwxres/animations/gangshangkaihua_tx.atlas",
    //mjgangskh_txjson: "res/ui/kwxResource/newkwxres/animations/gangshangkaihua_tx.json",
    //mjgangskh_txpng: "res/ui/kwxResource/newkwxres/animations/gangshangkaihua_tx.png",
    //mjgangsp_txatlas: "res/ui/kwxResource/newkwxres/animations/gangshangpao_tx.atlas",
    //mjgangsp_txjson: "res/ui/kwxResource/newkwxres/animations/gangshangpao_tx.json",
    //mjgangsp_txpng: "res/ui/kwxResource/newkwxres/animations/gangshangpao_tx.png",
    //mjliang_txatlas: "res/ui/kwxResource/newkwxres/animations/liang_tx.atlas",
    //mjliang_txjson: "res/ui/kwxResource/newkwxres/animations/liang_tx.json",
    //mjliang_txpng: "res/ui/kwxResource/newkwxres/animations/liang_tx.png",
    //mjhu_txatlas: "res/ui/kwxResource/newkwxres/animations/hu_tx.atlas",
    //mjhu_txjson: "res/ui/kwxResource/newkwxres/animations/hu_tx.json",
    //mjhu_txpng: "res/ui/kwxResource/newkwxres/animations/hu_tx.png",
    //mjhu_tx2png: "res/ui/kwxResource/newkwxres/animations/hu_tx2.png",
    wanfaImg10:"res/niuniuRes/wanfaImg10.png",
    kwxtable: "res/ui/kwxTable.json",
    NotifyCard: "res/ui/KwxNotifyCard.json",
    NoticeExit: "res/ui/NoticeExit.json",
    //addbonuschoose:"res/ui/KwxAddBonusChoose.json",
    kwxResultoneui: "res/ui/KwxEndPlayWindow.json",
    kwxResultui: "res/ui/KwxAllEnd.json",
    kwxRecordjson: "res/ui/kwxReplayWindow.json",
    wait_skeleton:"res/kwxAnimation/wait.atlas",
    wait_json:"res/kwxAnimation/wait.json",
    wait_png:"res/kwxAnimation/wait.png",
    waitgold_skeleton:"res/kwxAnimation/goldwait.atlas",
    waitgold_json:"res/kwxAnimation/goldwait.json",
    waitgold_png:"res/kwxAnimation/goldwait.png",
    background_png: "res/ui/kwxResource/png/fangkaxiaobeijing.png",

    gang_scr0: "res/game/kwx/ui/gangf@4x.png",
    gang_scr1: "res/game/kwx/ui/gangf@2x.png",
    gang_scr2: "res/game/kwx/ui/gangf@1x.png",
    gang_scr3: "res/game/kwx/ui/gangz@1x.png",
    gang_scr4: "res/game/kwx/ui/gangz@2x.png",
    gang_scr5: "res/game/kwx/ui/gangz@4x.png",
    gang_scr6: "res/game/kwx/ui/gangz@8x.png",

    pointToSelf: "res/ui/kwxResource/newkwxres/bei.png",

    pointToNext: "res/game/kwx/ui/dong.png",
    pointToPrev: "res/game/kwx/ui/xi.png",
    liangpai_wrong: "res/game/kwx/ui/liangpai_wrong.png",

    btnAnimatejson9:"res/btnAnimate/kawuxing.json",
    btnAnimateatlas9:"res/btnAnimate/kawuxing.atlas",
    btnAnimatepng9:"res/btnAnimate/kawuxing.png",

    mjcardsplist:"res/commonUi/mjcardsplist.plist",
    mjcardspng:"res/commonUi/mjcardsplist.png",

    btn_quitExit:"res/commonUi/room/btn_quitExit@2x.png",

    resulthu:"res/ui/kwxResource/newkwxres/yyjb_img_hu@2x.png",

    resultdianpao:"res/game/kwx/ui/yyjb_img_fangpao@2x.png",
    resulthuangz:"res/game/kwx/ui/yyjb_img_huangz@2x.png",
    resultpeihu:"res/game/kwx/ui/yyjb_img_peihu@2x.png",

    resultzimo:"res/ui/kwxResource/newkwxres/goldjiesuan/yyjb_img_zimo@2x.png",

    iconfenpng:"res/game/kwx/ui/img_fen.png",
    kwx_hubg_tishi:"res/game/kwx/ui/kwx_bg_tishi@2x.png",
    png_ting: "res/game/kwx/ui/kwx_jiaoting.png",
    png_liang: "res/game/kwx/ui/kwx_jiaolia.png",

    kwx_img_hutips:"res/ui/kwxResource/newkwxres/kwx_img_hu@2x.png",
    record_hu: "res/ui/kwxResource/newkwxres/hu.png",
    record_gang: "res/ui/kwxResource/newkwxres/gang.png",
    record_liang: "res/ui/kwxResource/newkwxres/kwx_liang.png",

    record_peng: "res/ui/kwxResource/newkwxres/peng.png",

    kwx_cardzz:"res/game/kwx/ui/kwx_cardzhezhao.png",
    //卡五星金币场
    kwxGoldend:"res/ui/KwxGoldend.json",

    kwxNameIcon:"res/commonUi/glodCreate/yyjb_title_kwx@2x.png",
    kwx0_0:"res/commonUi/glodCreate/yyjb_img_mm2@2x.png",
    kwx0_1:"res/commonUi/glodCreate/yyjb_img_mm1@2x.png",
    kwx1_0:"res/commonUi/glodCreate/yyjb_img_bmm2@2x.png",
    kwx1_1:"res/commonUi/glodCreate/yyjb_img_bmm1@2x.png",
    kwx2_0:"res/commonUi/glodCreate/yyjb_img_qpd2@2x.png",
    kwx2_1:"res/commonUi/glodCreate/yyjb_img_qpd1@2x.png",
    kwx3_0:"res/commonUi/glodCreate/yyjb_img_qpdb2@2x.png",
    kwx3_1:"res/commonUi/glodCreate/yyjb_img_qpdb1@2x.png",
    kwx4_0:"res/commonUi/glodCreate/yyjb_img_slwf2@2x.png",
    kwx4_1:"res/commonUi/glodCreate/yyjb_img_slwf1@2x.png",

    kwxlose:"res/game/kwx/ui/yyjb_img_lose@2x.png",

    //金币场战绩
    goldzhanji: "res/ui/goldZhanji.json",
    goldzhanjcellbg:"res/ui/goldres/yyjb_bg_zhanji@2x.png",
    //common
    playMenuView:"res/ui/playMenuLayer.json",
    goldTimeBar:"res/game/nysgold/ui/ptj_img_jishi@2x.png",
    //五子棋
    goldWzqTable:"res/ui/wzqGoldTable.json",
    wzqSetScore:"res/ui/wzqSetScore.json",
    wzqJoinRoomUi: "res/ui/wzqGoldCreateRoom.json",
    wzqChessArea:"res/ui/wzqResource/wzqChessArea.png",
    wzqChessBlack:"res/ui/wzqResource/yyjb_img_black@2x.png",

    wzqChessWhite:"res/game/wzq/ui/yyjb_img_white@2x.png",

    wzqNum0:"res/ui/wzqResource/goldCreateRoom/yyjb_img_zero@2x.png",
    wzqNum1:"res/ui/wzqResource/goldCreateRoom/yyjb_img_invite@2x.png",
    wzqNum2:"res/ui/wzqResource/goldCreateRoom/yyjb_img_two@2x.png",
    wzqNum3:"res/ui/wzqResource/goldCreateRoom/yyjb_img_three@2x.png",
    wzqNum4:"res/ui/wzqResource/goldCreateRoom/yyjb_img_four@2x.png",
    wzqNum5:"res/ui/wzqResource/goldCreateRoom/yyjb_img_five@2x.png",
    wzqNum6:"res/ui/wzqResource/goldCreateRoom/yyjb_img_six@2x.png",
    wzqNum7:"res/ui/wzqResource/goldCreateRoom/yyjb_img_seven@2x.png",
    wzqNum8:"res/ui/wzqResource/goldCreateRoom/yyjb_img_eight@2x.png",
    wzqNum9:"res/ui/wzqResource/goldCreateRoom/yyjb_img_nine@2x.png",

    //三张牌金币场
    szpNameIcon:"res/game/zjhgold/ui/yyjb_title_psz@2x.png",
    szp0_0:"res/game/zjhgold/ui/yyjb_img_jdwf2@2x.png",
    szp0_1:"res/game/zjhgold/ui/yyjb_img_jdwf1@2x.png",
    szp1_0:"res/game/zjhgold/ui/yyjb_img_fkwf2@2x.png",
    szp1_1:"res/game/zjhgold/ui/yyjb_img_fkwf1@2x.png",

    zjhtableGold:"res/ui/zjhtablefk_gold.json",
    headBorder:"res/ui/commonCells/commonPic/inRoomSamePic/zjh_touxiang.png",

    baofangszptitle:"res/commonUi/glodCreate/yyjp_img_psz@2x_bf.png",
    baofangdstitle:"res/commonUi/goldScene/yyjb_title_ds@2x.png",
    baofangdstitlenys:"res/commonUi/goldScene/yyjb_title_nys@2x.png",

    spineFail_j: "res/commonAnim/fail.json",
    spineFail_a: "res/commonAnim/fail.atlas",
    spineFail_p: "res/commonAnim/fail.png",
    spineWin_j: "res/commonAnim/victory.json",
    spineWin_a: "res/commonAnim/victory.atlas",
    spineWin_p1: "res/commonAnim/victory.png",
    spineWin_p2: "res/commonAnim/victory2.png",
    spinecrown_j: "res/commonAnim/crown.json",
    spinecrown_a: "res/commonAnim/crown.atlas",
    spinecrown_p: "res/commonAnim/crown.png",
    duijukaishi_j:"res/commonAnim/duijukaishi2.json",
    duijukaishi_a:"res/commonAnim/duijukaishi2.atlas",
    duijukaishi_p:"res/commonAnim/duijukaishi2.png",

    //牛元帅金币场
    callBet0:"res/ui/goldNYS/loadRes/nn_img_q0@2x.png",
    callBet2:"res/ui/goldNYS/loadRes/nn_img_q2@2x.png",
    callBet1:"res/game/nysgold/ui/nn_img_q1@2x.png",
    callBet3:"res/game/nysgold/ui/nn_img_q3@2x.png",
    callBet4:"res/game/nysgold/ui/nn_img_q4@2x.png",

    callScore1:"res/game/nysgold/ui/nn_img_b1@2x.png",
    callScore2:"res/game/nysgold/ui/nn_img_b2@2x.png",
    callScore3:"res/game/nysgold/ui/nn_img_b3@2x.png",
    callScore4:"res/game/nysgold/ui/nn_img_b4@2x.png",
    callScore5:"res/game/nysgold/ui/nn_img_b5@2x.png",

    randomLightH:"res/game/nysgold/ui/light1@2x.png",
    randomLightP:"res/game/nysgold/ui/light2@2x.png",

    jsonNiu0: "res/game/nysgold/animate/meiniu.json",
    atlasNiu0: "res/game/nysgold/animate/meiniu.atlas",
    jsonNiu91: "res/game/nysgold/animate/niuyi.json",
    atlasNiu91: "res/game/nysgold/animate/niuyi.atlas",
    jsonNiu92: "res/game/nysgold/animate/niuer.json",
    atlasNiu92: "res/game/nysgold/animate/niuer.atlas",
    jsonNiu93: "res/game/nysgold/animate/niusan.json",
    atlasNiu93: "res/game/nysgold/animate/niusan.atlas",
    jsonNiu94: "res/game/nysgold/animate/niusi.json",
    atlasNiu94: "res/game/nysgold/animate/niusi.atlas",
    jsonNiu95: "res/game/nysgold/animate/niuwu.json",
    atlasNiu95: "res/game/nysgold/animate/niuwu.atlas",
    jsonNiu96: "res/game/nysgold/animate/niuliu.json",
    atlasNiu96: "res/game/nysgold/animate/niuliu.atlas",
    jsonNiu97: "res/game/nysgold/animate/niuqi.json",
    atlasNiu97: "res/game/nysgold/animate/niuqi.atlas",
    jsonNiu98: "res/game/nysgold/animate/niuba.json",
    atlasNiu98: "res/game/nysgold/animate/niuba.atlas",
    jsonNiu99: "res/game/nysgold/animate/niujiu.json",
    atlasNiu99: "res/game/nysgold/animate/niujiu.atlas",
    aaa0:"res/game/nysgold/animate/meiniu.png",
    aaa1:"res/game/nysgold/animate/niuyi.png",
    aaa2:"res/game/nysgold/animate/niuer.png",
    aaa3:"res/game/nysgold/animate/niusan.png",
    aaa4:"res/game/nysgold/animate/niusi.png",
    aaa5:"res/game/nysgold/animate/niuwu.png",
    aaa6:"res/game/nysgold/animate/niuliu.png",
    aaa7:"res/game/nysgold/animate/niuqi.png",
    aaa8:"res/game/nysgold/animate/niuba.png",
    aaa9:"res/game/nysgold/animate/niujiu.png",
    aaa10:"res/game/nysgold/animate/niuniu.png",
    aaa11:"res/game/nysgold/animate/wuhuaniu.png",
    aaa12:"res/game/nysgold/animate/zhadanniu.png",
    aaa13:"res/game/nysgold/animate/wuxiaoniu.png",
    aaa14:"res/game/nysgold/animate/shunjinniu.png",
    aaa15:"res/game/nysgold/animate/tonghuaniu.png",
    aaa16:"res/game/nysgold/animate/shunziniu.png",
    aaa17:"res/game/nysgold/animate/huluniu.png",
    jsonNiu100: "res/game/nysgold/animate/niuniu.json",
    atlasNiu100: "res/game/nysgold/animate/niuniu.atlas",
    jsonNiu700: "res/game/nysgold/animate/zhadanniu.json",
    atlasNiu700: "res/game/nysgold/animate/zhadanniu.atlas",
    jsonNiu300: "res/game/nysgold/animate/wuhuaniu.json",
    atlasNiu300: "res/game/nysgold/animate/wuhuaniu.atlas",
    jsonNiu500: "res/game/nysgold/animate/wuxiaoniu.json",
    atlasNiu500: "res/game/nysgold/animate/wuxiaoniu.atlas",
    jsonNiu600: "res/game/nysgold/animate/huluniu.json",
    atlasNiu600: "res/game/nysgold/animate/huluniu.atlas",
    jsonNiu800: "res/game/nysgold/animate/shunjinniu.json",
    atlasNiu800: "res/game/nysgold/animate/shunjinniu.atlas",
    jsonNiu200: "res/game/nysgold/animate/shunziniu.json",
    atlasNiu200: "res/game/nysgold/animate/shunziniu.atlas",
    jsonNiu400: "res/game/nysgold/animate/tonghuaniu.json",
    atlasNiu400: "res/game/nysgold/animate/tonghuaniu.atlas",

    winGold:"res/ui/winGold.json",
    lostGold:"res/ui/lostGold.json",
    jiaLogo:"res/ui/pingtianjiu/ptj_jia@2x.png",

    jianLogo:"res/game/pingtianjiu/ui/ptj_jian@2x.png",

    startAnim:"res/ui/startAnim.json",

    niuniuState0:"res/game/nysgold/ui/nn_img_waitting@2x.png",
    niuniuState1:"res/game/nysgold/ui/nn_img_qz@2x.png",
    niuniuState2:"res/game/nysgold/ui/nn_img_xz@2x.png",
    niuniuState3:"res/game/nysgold/ui/nn_img_pp@2x.png",
    niuniuState4:"res/game/nysgold/ui/nn_img_ready@2x.png",

    nysoneBetBtnImg:"res/ui/niuniuPic/jxnn_btn_fraction1.png",
    nysQiangZhuangBtnImg:"res/ui/niuniuPic/img_qiang@2x.png",

    jsonStartAnim1:"res/commonAnim/kaishi1.json",
    atlasStartAnim1:"res/commonAnim/kaishi1.atlas",
    pngStartAnim1:"res/commonAnim/kaishi1.png",
    gunzi:"res/commonAnim/gunzi.png",

    nysDifen50:"res/game/nysgold/ui/img_50.png",
    nysDifen100:"res/game/nysgold/ui/img_100.png",
    nysDifen200:"res/game/nysgold/ui/img_200.png",
    nysDifen300:"res/game/nysgold/ui/img_300.png",
    nysDifen500:"res/game/nysgold/ui/img_500.png",
    nysDifen1000:"res/game/nysgold/ui/img_1000.png",
    //=================名品汇=====================
    //onlineList:"res/ui/A_sxdb/online.png",
    //resultType0:"res/game/sxdb/ui/benchi_big0.png",
    //resultType1:"res/game/sxdb/ui/benchi_big1.png",
    //resultType2:"res/game/sxdb/ui/guchi_big2.png",
    //resultType3:"res/game/sxdb/ui/aimashi_big3.png",
    //resultType4:"res/game/sxdb/ui/amani_big4.png",
    //resultType5:"res/game/sxdb/ui/shengluolan_big5.png",
    //resultType6:"res/game/sxdb/ui/lv_big6.png",
    //resultType7:"res/game/sxdb/ui/Dior_big7.png",
    //resultType8:"res/game/sxdb/ui/xiangnaier_big8.png",
    //resultType9:"res/game/sxdb/ui/laolis_big9.png",
    //
    //recordType0:"res/game/sxdb/ui/benchi_xiao0.png",
    //recordType1:"res/game/sxdb/ui/benchi_xiao1.png",
    //recordType2:"res/game/sxdb/ui/guchi_xiao2.png",
    //recordType3:"res/game/sxdb/ui/aimashi_xiao3.png",
    //recordType4:"res/game/sxdb/ui/amani_xiao4.png",
    //recordType5:"res/game/sxdb/ui/shengluolan_xiao5.png",
    //recordType6:"res/game/sxdb/ui/lv_xiao6.png",
    //recordType7:"res/game/sxdb/ui/Dior_xiao7.png",
    //recordType8:"res/game/sxdb/ui/xiangnaier_xiao8.png",
    //recordType9:"res/game/sxdb/ui/laolis_xiao9.png",
    //recordType2100:"res/game/sxdb/ui/img_tp.png",
    //recordType700:"res/game/sxdb/ui/img_ts.png",
    //ts_logo700:"res/game/sxdb/ui/img_ts.png",
    //ts_logo2100:"res/game/sxdb/ui/img_tp.png",
    //=================龙虎斗=====================
    lhdrecord0:"res/commonUi/lhd/ui/long.png",
    lhdrecord1:"res/commonUi/lhd/ui/hu.png",
    lhdrecord2:"res/commonUi/lhd/ui/he.png",
    lhdSlectImg:"res/ui/goldlhd/xugen.png",
    lhdNormalImg:"res/commonUi/lhd/ui/anniu2.png",
    lhdxzjs:"res/commonUi/lhd/ui/xzjs.png",
    lhdksxz:"res/commonUi/lhd/ui/ksxz.png",
    lhdrescolor0:"res/commonUi/lhd/ui/hongquan.png",
    lhdrescolor1:"res/commonUi/lhd/ui/lanquan.png",
    //=================一夜暴富====================
    //yybfrank0:"res/game/goldyybf/di1.png",
    //yybfrank1:"res/game/goldyybf/di2.png",
    //yybfrank2:"res/game/goldyybf/di3.png",

    //=================地穴探宝====================
    //dfh_fireList:"res/game/dafuhao/ui/dfh_huo.plist",
    //dfh_firepng:"res/game/dafuhao/ui/dfh_huo.png",
    //=================翻牌机====================
    //fpjType1:"res/ui/goldfpj/ui/shuang@2x.png",
    //fpjType2:"res/ui/goldfpj/ui/two@2x.png",
    //fpjType3:"res/ui/goldfpj/ui/three@2x.png",
    //fpjType4:"res/ui/goldfpj/ui/four@2x.png",
    //fpjType5:"res/ui/goldfpj/ui/five@2x.png",
    //fpjType6:"res/ui/goldfpj/ui/six@2x.png",
    //fpjType7:"res/ui/goldfpj/ui/seven@2x.png",
    //fpjType8:"res/ui/goldfpj/ui/eight@2x.png",
    //fpjType9:"res/ui/goldfpj/ui/nine@2x.png",
    //fpjType10:"res/ui/goldfpj/ui/ten@2x.png",
    //fpjsave:"res/ui/goldfpj/ui/@2x.png",

    //=================房卡跑的快====================
    pdk_losebg1:"res/ui/xiangjun/game/21-result/xjhy_bg_lose1@2x.png",
    pdk_losebg2:"res/ui/xiangjun/game/21-result/xjhy_bg_lose2@2x.png",
    zhenghao:"res/ui/xiangjun/game/21-result/xjhy_y_jia.png",
    fuhao:"res/ui/xiangjun/game/21-result/xjhy_b_jian.png",
    chatbg_lt: "res/ui/xiangjun/game/21-result/chatbg_lt.png",
    soundopen: "res/ui/xiangjun/game/21-result/soundOpen.png",
    img_input1:"res/ui/xiangjun/game/17-room/xjhy_bg_tishiyu@2x@2x.png",

    //=================十三水====================
    shi_sanshuiplist:"res/btnAnimate/shi_sanshui.plist",
    shi_sanshuipng:"res/btnAnimate/shi_sanshui.png",
    
    //=================龙珠探宝====================
    //curpage:"res/game/dragon/ui/allpage1.png",
    //dafaultpage:"res/game/dragon/ui/allpage.png",
    //dragon_itemPlist:"res/ui/dragon/hall/dragon_item.plist",
    //dragon_itemPng:"res/ui/dragon/hall/dragon_item.png",

    spebets2_0:"res/game/dragon/ui/spebets2_0.png",
    spebets3_0:"res/game/dragon/ui/spebets3_0.png",
    spebets4_0:"res/game/dragon/ui/spebets4_0.png",
    spebets5_0:"res/game/dragon/ui/spebets5_0.png",
    spebets10_0:"res/game/dragon/ui/spebets10_0.png",
    spebets2_1:"res/game/dragon/ui/spebets2_1.png",
    spebets3_1:"res/game/dragon/ui/spebets3_1.png",
    spebets4_1:"res/game/dragon/ui/spebets4_1.png",
    spebets5_1:"res/game/dragon/ui/spebets5_1.png",
    spebets10_1:"res/game/dragon/ui/spebets10_1.png",


    dragonChu_8_Plist:"res/game/dragon/animation/dragonChu_8.plist",
    dragonChu_8_Png:"res/game/dragon/animation/dragonChu_8.png",

    dragonAn_1_Plist:"res/game/dragon/animation/dragonAn_1.plist",
    dragonAn_2_Plist:"res/game/dragon/animation/dragonAn_2.plist",
    dragonAn_3_Plist:"res/game/dragon/animation/dragonAn_3.plist",
    dragonAn_4_Plist:"res/game/dragon/animation/dragonAn_4.plist",
    dragonAn_5_Plist:"res/game/dragon/animation/dragonAn_5.plist",
    dragonAn_6_Plist:"res/game/dragon/animation/dragonAn_6.plist",
    dragonAn_7_Plist:"res/game/dragon/animation/dragonAn_7.plist",
    dragonAn_8_Plist:"res/game/dragon/animation/dragonAn_8.plist",
    dragonAn_9_Plist:"res/game/dragon/animation/dragonAn_9.plist",
    dragonAn_10_Plist:"res/game/dragon/animation/dragonAn_10.plist",
    dragonAn_11_Plist:"res/game/dragon/animation/dragonAn_11.plist",

    dragonAn_1_Png:"res/game/dragon/animation/dragonAn_1.png",
    dragonAn_2_Png:"res/game/dragon/animation/dragonAn_2.png",
    dragonAn_3_Png:"res/game/dragon/animation/dragonAn_3.png",
    dragonAn_4_Png:"res/game/dragon/animation/dragonAn_4.png",
    dragonAn_5_Png:"res/game/dragon/animation/dragonAn_5.png",
    dragonAn_6_Png:"res/game/dragon/animation/dragonAn_6.png",
    dragonAn_7_Png:"res/game/dragon/animation/dragonAn_7.png",
    dragonAn_8_Png:"res/game/dragon/animation/dragonAn_8.png",
    dragonAn_9_Png:"res/game/dragon/animation/dragonAn_9.png",
    dragonAn_10_Png:"res/game/dragon/animation/dragonAn_10.png",
    dragonAn_11_Png:"res/game/dragon/animation/dragonAn_11.png",

    //=================摇塞子=====================
    //baoziImg:"res/game/yaosaizi/ui/bzw_img_green@2x.png",
    //danshuangImg:"res/game/yaosaizi/ui/bzw_img_danshuang@2x.png",
    //yszrecord0:"res/game/yaosaizi/ui/bzw_img_small@2x.png",
    //yszrecord2:"res/game/yaosaizi/ui/tzw_img_bao@2x.png",
    //yszrecord1:"res/game/yaosaizi/ui/bzw_img_big@2x.png",
    //yszresult0:"res/game/yaosaizi/ui/bzw_img_xiao.png",
    //yszresult1:"res/game/yaosaizi/ui/img_bz@2x.png",
    //yszresult2:"res/game/yaosaizi/ui/bzw_img_da.png",

    //=================单双=====================
    //goldToubao:"res/ui/A_toubaoTable.json",
    //goldToubaonew:"res/ui/A_toubaoTablenew.json",
    //chatMicLayerBzw:"res/ui/LookPlayerBZW.json",
    //reportTB:"res/ui/reportLayerTB.json",
    //tb_killPlist:"res/game/toubao/ui/tb_kill.plist",
    //tb_killPng:"res/game/toubao/ui/tb_kill.png",
    //sprkill:"res/game/toubao/ui/kill.png",
    //sprkill0:"res/game/toubao/ui/kill1.png",
    //sprkill1:"res/game/toubao/ui/kill2.png",
    //betlight:"res/game/toubao/ui/bet_light.png",
    //png_xysz:"res/game/toubao/ui/xysz.png",
    //betchiptb50:"res/game/coinRes/betchip5000.png",
    //betchiptb100:"res/game/coinRes/betchip10000.png",
    //betchiptb200:"res/game/coinRes/betchip20000.png",
    //betchiptb500:"res/game/coinRes/betchip50000.png",
    //betchiptb1000:"res/game/coinRes/betchip100000.png",
    //betchiptb5000:"res/game/coinRes/betchip500000.png",
    //tbresult0:"res/game/toubao/ui/tb_img_dan.png",
    //tbresult1:"res/game/toubao/ui/tb_img_shuang.png",

    //=================赛马=====================
    //horsepng_1:"res/ui/goldRacing/horse_1.png",
    //horseplist_1:"res/ui/goldRacing/horse_1.plist",
    //horsepng_2:"res/ui/goldRacing/horse_2.png",
    //horseplist_2:"res/ui/goldRacing/horse_2.plist",
    //horsepng_3:"res/ui/goldRacing/horse_3.png",
    //horseplist_3:"res/ui/goldRacing/horse_3.plist",
    //horsepng_4:"res/ui/goldRacing/horse_4.png",
    //horseplist_4:"res/ui/goldRacing/horse_4.plist",
    //horsepng_5:"res/ui/goldRacing/horse_5.png",
    //horseplist_5:"res/ui/goldRacing/horse_5.plist",
    //horsepng_6:"res/ui/goldRacing/horse_6.png",
    //horseplist_6:"res/ui/goldRacing/horse_6.plist",
    //racingNum1:"res/ui/goldRacing/1.png",
    //racingNum2:"res/game/racing/ui/2.png",
    //racingNum3:"res/game/racing/ui/3.png",
    //racingNum4:"res/game/racing/ui/4.png",
    //racingNum5:"res/game/racing/ui/5.png",
    //racingNum6:"res/game/racing/ui/6.png",
    //yybfwinroll: "res/game/racing/animate/goldyybf_ani.plist",
    //yybfwinrollpng: "res/game/racing/animate/goldyybf_ani.png",

    //=================豹子王=====================
    //betNormalImg:"res/ui/baoziWang/btn_default@2x.png",
    //betCannotImg:"res/ui/baoziWang/btn_grey@2x.png",
    //
    //betSlectImg:"res/game/leopardKing/ui/btn_pitchon@2x.png",
    //mdls:"res/game/leopardKing/ui/bzw_img_leave@2x.png",
    //dian1:"res/game/leopardKing/ui/bzw_img_1p@2x.png",
    //dian2:"res/game/leopardKing/ui/bzw_img_2p@2x.png",
    //dian3:"res/game/leopardKing/ui/bzw_img_3p@2x.png",
    //dian4:"res/game/leopardKing/ui/bzw_img_4p@2x.png",
    //dian5:"res/game/leopardKing/ui/bzw_img_5p@2x.png",
    //dian6:"res/game/leopardKing/ui/bzw_img_6p@2x.png",
    closeList:"res/game/leopardKing/ui/bzw_btn_player2@2x.png",
    //record0:"res/game/leopardKing/ui/bzw_img_small@2x.png",
    //record1:"res/game/leopardKing/ui/tzw_img_bao@2x.png",
    //record2:"res/game/leopardKing/ui/bzw_img_big@2x.png",
    //bzwKuang0:"res/game/leopardKing/ui/seat_head_01@2x.png",
    //
    //qxz:"res/ui/baoziWang/bzw_img_bet@2x.png",
    openList:"res/ui/baoziWang/bzw_btn_player@2x.png",
    //
    //greenImg:"res/game/leopardKing/ui/bzw_img_green@2x.png",
    //redImg:"res/game/leopardKing/ui/bzw_img_red@2x.png",
    //blueImg:"res/game/leopardKing/ui/bzw_img_blue@2x.png",
    //yellowImg:"res/game/leopardKing/ui/bzw_img_yellow@2x.png",
    //result0:"res/game/leopardKing/ui/bzw_img_xiao.png",
    //result2:"res/game/leopardKing/ui/bzw_img_da.png",
    //
    //result1:"res/ui/baoziWang/img_bz@2x.png",
    //
    //IMGdian1:"res/ui/baoziWang/zoushi/bzw_img_1dian@2x.png",
    //showdian4:"res/ui/baoziWang/zoushi/dian4.png",

    //IMGdian2:"res/game/leopardKing/ui/zoushi/bzw_img_2dian@2x.png",
    //IMGdian3:"res/game/leopardKing/ui/zoushi/bzw_img_3dian@2x.png",
    //IMGdian4:"res/game/leopardKing/ui/zoushi/bzw_img_4dian@2x.png",
    //IMGdian5:"res/game/leopardKing/ui/zoushi/bzw_img_5dian@2x.png",
    //IMGdian6:"res/game/leopardKing/ui/zoushi/bzw_img_6dian@2x.png",
    showdian3:"res/game/leopardKing/ui/zoushi/dian3.png",
    showdian5:"res/game/leopardKing/ui/zoushi/dian5.png",
    showdian6:"res/game/leopardKing/ui/zoushi/dian6.png",
    showdian7:"res/game/leopardKing/ui/zoushi/dian7.png",
    showdian8:"res/game/leopardKing/ui/zoushi/dian8.png",
    showdian9:"res/game/leopardKing/ui/zoushi/dian9.png",
    showdian10:"res/game/leopardKing/ui/zoushi/dian10.png",
    showdian11:"res/game/leopardKing/ui/zoushi/dian11.png",
    showdian12:"res/game/leopardKing/ui/zoushi/dian12.png",
    showdian13:"res/game/leopardKing/ui/zoushi/dian13.png",
    showdian14:"res/game/leopardKing/ui/zoushi/dian14.png",
    showdian15:"res/game/leopardKing/ui/zoushi/dian15.png",
    showdian16:"res/game/leopardKing/ui/zoushi/dian16.png",
    showdian17:"res/game/leopardKing/ui/zoushi/dian17.png",
    showdian18:"res/game/leopardKing/ui/zoushi/dian18.png",

    jsondayingjia02:"res/game/leopardKing/animate/dayingjia02.json",
    atlasdayingjia02:"res/game/leopardKing/animate/dayingjia02.atlas",
    pngdayingjia02:"res/game/leopardKing/animate/dayingjia02.png",
    dayingjia:"res/game/leopardKing/animate/dayingjia.png",
    jsonbaozi:"res/game/leopardKing/animate/baozi.json",
    atlasbaozi:"res/game/leopardKing/animate/baozi.atlas",
    pngbaozi:"res/game/leopardKing/animate/baozi.png",
    jsontouzhong:"res/game/leopardKing/animate/touzhong.json",
    atlastouzhong:"res/game/leopardKing/animate/touzhong.atlas",
    pngtouzhong:"res/game/leopardKing/animate/touzhong.png",

    chipPlist:"res/niuniuRes/chip.plist",
    chippng:"res/niuniuRes/chip.png",

    bzwKuang1:"res/ui/baoziWang/seat_head_02@2x.png",

    sex0:"res/commonUi/chatMic/imgMan@2x.png",
    sex1:"res/commonUi/chatMic/imgWoman@2x.png",

    player8Bg:"res/commonUi/room/bg_zhuomian@2x.png",
    //==========================
    nysNameIcon:"res/commonUi/glodCreate/yyjb_title_nys@2x.png",//LSH怎么搞的有重名啊啊啊啊啊啊

    nys0_0:"res/commonUi/glodCreate/yyjb_img_kpqz1@2x.png",
    nys0_1:"res/commonUi/glodCreate/yyjb_img_kpqz2@2x.png",
    nys1_0:"res/commonUi/glodCreate/yyjb_img_kptz1@2x.png",
    nys1_1:"res/commonUi/glodCreate/yyjb_img_kptz2@2x.png",
    nys2_0:"res/commonUi/glodCreate/yyjb_img_brwf1@2x.png",
    nys2_1:"res/commonUi/glodCreate/yyjb_img_brwf2@2x.png",
    pdk0_0:"res/commonUi/glodCreate/yyjb_img_erwf2@2x.png",
    pdk0_1:"res/commonUi/glodCreate/yyjb_img_erwf1@2x.png",
    pdk1_0:"res/commonUi/glodCreate/yyjb_img_srwf2@2x.png",
    pdk1_1:"res/commonUi/glodCreate/yyjb_img_srwf1@2x.png",

    //排行榜
    jsonCup1: "res/roomAnimate/goldRankingList/cup1.json",
    atlasCup1: "res/roomAnimate/goldRankingList/cup1.atlas",
    pngCup1: "res/roomAnimate/goldRankingList/cup1.png",
    jsonCup2: "res/roomAnimate/goldRankingList/cup2.json",
    atlasCup2: "res/roomAnimate/goldRankingList/cup2.atlas",
    pngCup2: "res/roomAnimate/goldRankingList/cup2.png",
    jsonCup3: "res/roomAnimate/goldRankingList/cup3.json",
    atlasCup3: "res/roomAnimate/goldRankingList/cup3.atlas",
    pngCup3: "res/roomAnimate/goldRankingList/cup3.png",

    playerHead:"res/ui/commonCells/commonPic/hallPic/goldScene/yyjb_bg_head1@2x.png",
    rankCellBg:"res/ui/goldRankingList/yyjb_bg_list2@2x.png",
    cuFont:"res/ui/Font/FZY4JW_0569.TTF",

    //商城
    duihuanTitle:"res/commonUi/goldShop/yyjb_title_shop1@2x.png",
    //金币场大厅
    jsonPSZ: "res/roomAnimate/pinsanzhang.json",
    atlasPSZ: "res/roomAnimate/pinsanzhang.atlas",
    pngPSZ: "res/roomAnimate/pinsanzhang.png",
    jsonNYS: "res/roomAnimate/niuyuanshuai2.json",
    atlasNYS: "res/roomAnimate/niuyuanshuai2.atlas",
    pngNYS: "res/roomAnimate/niuyuanshuai2.png",
    jsongold: "res/roomAnimate/jinbitubiao.json",
    atlasgold: "res/roomAnimate/jinbitubiao.atlas",
    pnggold: "res/roomAnimate/jinbitubiao.png",

    szpPrevNameIcon:"res/commonUi/goldScene/yyjb_title_psz@2x.png",
    nyxPrevNameIcon:"res/commonUi/goldScene/yyjb_title_nys@2x.png",//LSH怎么搞的有重名啊啊啊啊啊啊
    kwxPrevNameIcon:"res/commonUi/goldScene/yyjb_title_kwx@2x.png",
    bzwPrevNameIcon:"res/commonUi/goldScene/yyjb_title_bzw@2x.png",
    ttzTabNameIcon:"res/commonUi/goldScene/yyjb_title_ttz1@2x.png",
    ptjTabNameIcon:"res/commonUi/goldScene/yyjb_title_ptj@2x.png",
    pdkTabNameIcon:"res/commonUi/goldScene/yyjb_title_pdk@2x.png",
    dsTabNameIcon:"res/commonUi/goldScene/yyjb_title_ds@2x.png",

    //ttzDaTabNameIcon1:"res/commonUi/glodCreate/yyjb_img_wrwf1@2x.png",
    //ttzDaTabNameIcon2:"res/commonUi/glodCreate/yyjb_img_wrwf2@2x.png",
    //
    //ptjDaTabNameIcon1:"res/commonUi/glodCreate/yyjb_img_dpj1@2x.png",
    //ptjDaTabNameIcon2:"res/commonUi/glodCreate/yyjb_img_dpj2@2x.png",
    //ptjxiaoTabNameIcon1:"res/commonUi/glodCreate/yyjb_img_xpj1@2x.png",
    //ptjxiaoTabNameIcon2:"res/commonUi/glodCreate/yyjb_img_xpj2@2x.png",

    //bzwDaTabNameIcon1:"res/commonUi/glodCreate/yyjb_img_ptc1@2x.png",
    //bzwDaTabNameIcon2:"res/commonUi/glodCreate/yyjb_img_ptc2@2x.png",
    //bzwxiaoTabNameIcon1:"res/commonUi/glodCreate/yyjb_img_fhc1.png",
    //bzwxiaoTabNameIcon2:"res/commonUi/glodCreate/yyjb_img_fhc2@2x.png",

    szpWay_0:"res/ui/commonCells/commonPic/createPic/goldCreate/yyjb_btn_jdwf@2x.png",
    kwxWay_1:"res/ui/commonCells/commonPic/createPic/goldCreate/yyjb_btn_bmmwf.png",

    kwxWay_0:"res/commonUi/glodCreate/yyjb_btn_mmwf.png",
    kwxWay_2:"res/commonUi/glodCreate/yyjb_btn_qpdmm.png",
    kwxWay_3:"res/commonUi/glodCreate/yyjb_btn_qpdbmm.png",
    kwxWay_4:"res/commonUi/glodCreate/yyjb_btn_slwf.png",
    szpWay_1:"res/commonUi/glodCreate/yyjb_btn_gksz@2x.png",
    nysWay_0:"res/commonUi/glodCreate/yyjb_btn_kpqz@2x.png",
    nysWay_1:"res/commonUi/glodCreate/yyjb_btn_zyqz@2x.png",
    nysWay_2:"res/commonUi/glodCreate/yyjb_btn_brmp@2x.png",
    //ptjWay_0:"res/commonUi/glodCreate/yyjb_btn_dpj@2x.png",
    //ptjWay_1:"res/commonUi/glodCreate/yyjb_btn_xpj@2x.png",
    //bzwWay_0:"res/commonUi/glodCreate/btn_ptc@2x.png",
    //bzwWay_1:"res/commonUi/glodCreate/yyjb_btn_fhc@2x.png",
    ebgWay_0:"res/commonUi/glodCreate/yyjb_ebg_ptc@2x.png",
    ebgWay_1:"res/commonUi/glodCreate/yyjb_ebg_fhc@2x.png",
    dsWay_0:"res/commonUi/glodCreate/ds_bairen.png",

    game_coin:"res/ui/goldNYS/nn_img_gold@2x.png",

    goldRoomMvJson:"res/roomAnimate/meinv.json",
    goldRoomMvAtlas:"res/roomAnimate/meinv.atlas",
    goldRoomMvPng:"res/roomAnimate/meinv.png",

    //牛元帅房卡场
    nysDYJ:"res/ui/commonCells/commonPic/simpleEndPic/yyjb_img_dyj@2x.png",
    nysTH:"res/commonUi/end/yyjb_img_th@2x.png",

    txpmd_json:"res/game/nys/animate/txpmd.json",
    txpmd_atlas:"res/game/nys/animate/txpmd.atlas",
    txpmd_png:"res/game/nys/animate/txpmd.png",

    //二八杠
    ebgchipPlist:"res/game/erbagang/ui/ebgchip.plist",
    ebgchipPng:"res/game/erbagang/ui/ebgchip.png",
    ebgdianPlist:"res/game/erbagang/ui/ebgdian.plist",
    ebgdianPng:"res/game/erbagang/ui/ebgdian.png",
    ebglose:"res/game/erbagang/ui/28g_fu.png",
    ebgmdls:"res/game/erbagang/ui/28g_img_leave.png",

    ebgwin:"res/ui/A_erbagang/28g_sheng.png",
    ebgClick:"res/game/erbagang/ui/28g_img_yellow2.png",

    ebgqxz:"res/ui/A_erbagang/28g_img_bet.png",
    betchip10:"res/game/erbagang/ui/betchip10.png",
    betchip20:"res/game/erbagang/ui/betchip20.png",
    betchip50:"res/game/erbagang/ui/betchip50.png",
    betchip100:"res/game/erbagang/ui/betchip100.png",
    betchip200:"res/game/erbagang/ui/betchip200.png",
    betchip500:"res/game/erbagang/ui/betchip500.png",
    betchip1000:"res/game/erbagang/ui/betchip1000.png",

    ebgzcjson:"res/game/erbagang/animate/zc.json",
    ebgzcatlas:"res/game/erbagang/animate/zc.atlas",
    ebgzcpng:"res/game/erbagang/animate/zc.png",

    ebgendAnim1json:"res/game/erbagang/animate/zjts.json",
    ebgendAnim1atlas:"res/game/erbagang/animate/zjts.atlas",
    ebgendAnim1png:"res/game/erbagang/animate/zjts.png",

    ebgendAnim2json:"res/game/erbagang/animate/zjtp.json",
    ebgendAnim2atlas:"res/game/erbagang/animate/zjtp.atlas",
    ebgendAnim2png:"res/game/erbagang/animate/zjtp.png",

    //跑得快
    roler0Json:"res/game/paodekuai/animate/juese01.json",
    roler0Atlas:"res/game/paodekuai/animate/juese01.atlas",
    roler0Png:"res/game/paodekuai/animate/juese01.png",
    roler1Json:"res/game/paodekuai/animate/juese02.json",
    roler1Atlas:"res/game/paodekuai/animate/juese02.atlas",
    roler1Png:"res/game/paodekuai/animate/juese02.png",
    roler2Json:"res/game/paodekuai/animate/juese03.json",
    roler2Atlas:"res/game/paodekuai/animate/juese03.atlas",
    roler2Png:"res/game/paodekuai/animate/juese03.png",

    readyImg:"res/ui/niuniuPic/operate_prepare@2x.png",
    buyaoImg:"res/game/paodekuai/ui/img_buchu.png",
    pdktishiBg:"res/game/paodekuai/ui/brnn_beginbet@2x.png",

    feijiJson:"res/game/paodekuai/animate/feiji.json",
    feiji1Atlas:"res/game/paodekuai/animate/feiji.atlas",
    feiji1Png:"res/game/paodekuai/animate/feiji.png",
    feiji2Png:"res/game/paodekuai/animate/feiji2.png",
    feiji3Png:"res/game/paodekuai/animate/feiji3.png",

    shunziduiziJson:"res/game/paodekuai/animate/shunziduizi.json",
    shunziduiziAtlas:"res/game/paodekuai/animate/shunziduizi.atlas",
    shunziduiziPng:"res/game/paodekuai/animate/shunziduizi.png",

    zhadanJson:"res/game/paodekuai/animate/zhadan.json",
    zhadanAtlas:"res/game/paodekuai/animate/zhadan.atlas",
    zhadanPng:"res/game/paodekuai/animate/zhadan.png",

    pdkFirstLogo:"res/game/paodekuai/ui/img_shouchu.png",
    buyao0_0:"res/game/paodekuai/ui/buyao1.png",
    buyao0_1:"res/game/paodekuai/ui/buyao.png",
    buyao1_0:"res/game/paodekuai/ui/guo1.png",
    buyao1_1:"res/game/paodekuai/ui/guo.png",
    buyao2_0:"res/game/paodekuai/ui/yaobuqi1.png",
    buyao2_1:"res/game/paodekuai/ui/yaobuqi.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}

var g_magic_chat = {
    magic_chat_1_1_json: "res/btnAnimate/renjidan/renjidan1.json",
    magic_chat_1_1_atlas: "res/btnAnimate/renjidan/renjidan1.atlas",
    magic_chat_1_1_png: "res/btnAnimate/renjidan/renjidan1.png",
    magic_chat_1_2_json: "res/btnAnimate/renjidan/renjidan2.json",
    magic_chat_1_2_atlas: "res/btnAnimate/renjidan/renjidan2.atlas",
    magic_chat_1_2_png: "res/btnAnimate/renjidan/renjidan2.png",
    magic_chat_2_1_json: "res/btnAnimate/tuoxie/tuoxie1.json",
    magic_chat_2_1_atlas: "res/btnAnimate/tuoxie/tuoxie1.atlas",
    magic_chat_2_1_png: "res/btnAnimate/tuoxie/tuoxie1.png",
    magic_chat_2_2_json: "res/btnAnimate/tuoxie/tuoxie2.json",
    magic_chat_2_2_atlas: "res/btnAnimate/tuoxie/tuoxie2.atlas",
    magic_chat_2_2_png: "res/btnAnimate/tuoxie/tuoxie2.png",
    magic_chat_3_1_json: "res/btnAnimate/dianzan/dianzan1.json",
    magic_chat_3_1_atlas: "res/btnAnimate/dianzan/dianzan1.atlas",
    magic_chat_3_1_png: "res/btnAnimate/dianzan/dianzan1.png",
    magic_chat_3_2_json: "res/btnAnimate/dianzan/dianzan2.json",
    magic_chat_3_2_atlas: "res/btnAnimate/dianzan/dianzan2.atlas",
    magic_chat_3_2_png: "res/btnAnimate/dianzan/dianzan2.png",
    magic_chat_4_1_json: "res/btnAnimate/xianwen/xianwen1.json",
    magic_chat_4_1_atlas: "res/btnAnimate/xianwen/xianwen1.atlas",
    magic_chat_4_1_png: "res/btnAnimate/xianwen/xianwen1.png",
    magic_chat_4_2_json: "res/btnAnimate/xianwen/xianwen2.json",
    magic_chat_4_2_atlas: "res/btnAnimate/xianwen/xianwen2.atlas",
    magic_chat_4_2_png: "res/btnAnimate/xianwen/xianwen2.png",
    magic_chat_5_1_json: "res/btnAnimate/xianhua/xianhua1.json",
    magic_chat_5_1_atlas: "res/btnAnimate/xianhua/xianhua1.atlas",
    magic_chat_5_1_png: "res/btnAnimate/xianhua/xianhua1.png",
    magic_chat_5_2_json: "res/btnAnimate/xianhua/xianhua2.json",
    magic_chat_5_2_atlas: "res/btnAnimate/xianhua/xianhua2.atlas",
    magic_chat_5_2_png: "res/btnAnimate/xianhua/xianhua2.png",

};

for (var i in g_magic_chat) {
    g_resources.push(g_magic_chat[i]);
};

var g_chat_expression = {
    expression0_json:"res/expresssion/bishi.json",
    expression0_atlas:"res/expresssion/bishi.atlas",
    expression0_png:"res/expresssion/bishi.png",
    expression1_json:"res/expresssion/bizui.json",
    expression1_atlas:"res/expresssion/bizui.atlas",
    expression1_png:"res/expresssion/bizui.png",
    expression2_json:"res/expresssion/daku.json",
    expression2_atlas:"res/expresssion/daku.atlas",
    expression2_png:"res/expresssion/daku.png",
    expression3_json:"res/expresssion/danu.json",
    expression3_atlas:"res/expresssion/danu.atlas",
    expression3_png:"res/expresssion/danu.png",
    expression4_json:"res/expresssion/daxiao.json",
    expression4_atlas:"res/expresssion/daxiao.atlas",
    expression4_png:"res/expresssion/daxiao.png",
    expression5_json:"res/expresssion/jianxiao.json",
    expression5_atlas:"res/expresssion/jianxiao.atlas",
    expression5_png:"res/expresssion/jianxiao.png",
    expression6_json:"res/expresssion/jingya.json",
    expression6_atlas:"res/expresssion/jingya.atlas",
    expression6_png:"res/expresssion/jingya.png",
    expression7_json:"res/expresssion/lenghan.json",
    expression7_atlas:"res/expresssion/lenghan.atlas",
    expression7_png:"res/expresssion/lenghan.png",
    expression8_json:"res/expresssion/paishou.json",
    expression8_atlas:"res/expresssion/paishou.atlas",
    expression8_png:"res/expresssion/paishou.png",
    expression9_json:"res/expresssion/sexiao.json",
    expression9_atlas:"res/expresssion/sexiao.atlas",
    expression9_png:"res/expresssion/sexiao.png",
    expression10_json:"res/expresssion/shaoxiang.json",
    expression10_atlas:"res/expresssion/shaoxiang.atlas",
    expression10_png:"res/expresssion/shaoxiang.png",
    expression11_json:"res/expresssion/shuizhao.json",
    expression11_atlas:"res/expresssion/shuizhao.atlas",
    expression11_png:"res/expresssion/shuizhao.png",
    expression12_json:"res/expresssion/tushe.json",
    expression12_atlas:"res/expresssion/tushe.atlas",
    expression12_png:"res/expresssion/tushe.png",
    expression13_json:"res/expresssion/tuxue.json",
    expression13_atlas:"res/expresssion/tuxue.atlas",
    expression13_png:"res/expresssion/tuxue.png",
    expression14_json:"res/expresssion/wunai.json",
    expression14_atlas:"res/expresssion/wunai.atlas",
    expression14_png:"res/expresssion/wunai.png",
    expression15_json:"res/expresssion/xiaoku.json",
    expression15_atlas:"res/expresssion/xiaoku.atlas",
    expression15_png:"res/expresssion/xiaoku.png",
    expression16_json:"res/expresssion/xingyun.json",
    expression16_atlas:"res/expresssion/xingyun.atlas",
    expression16_png:"res/expresssion/xingyun.png",
    expression17_json:"res/expresssion/yiwen.json",
    expression17_atlas:"res/expresssion/yiwen.atlas",
    expression17_png:"res/expresssion/yiwen.png",
    expression18_json:"res/expresssion/zaijian.json",
    expression18_atlas:"res/expresssion/zaijian.atlas",
    expression18_png:"res/expresssion/zaijian.png",
    expression19_json:"res/expresssion/zhuakuang.json",
    expression19_atlas:"res/expresssion/zhuakuang.atlas",
    expression19_png:"res/expresssion/zhuakuang.png",
};

for (var i in g_chat_expression) {
    g_resources.push(g_chat_expression[i]);
};



var g_chatstr = ["快点啊，都等的我的花儿都谢了",
    "又断线啦？网络怎么这么差",
    "不要走,决战到天亮",
    "你的牌打得太好了",
    "你是妹妹还是哥哥啊",
    "和你合作真实太愉快了",
    "大家好，很高兴见到各位",
    "各位不好意思，我得离开一下",
    "不要吵了，不要吵了，吵啥嘛吵，专心玩游戏",];

var g_chatstr_sl = ["666，获得了手气王，不要太羡慕！",
    "哎~运气好，没办法！",
    "常在河边走，哪有不中雷！",
    "大伙继续啊，扫雷到底！",
    "哥们快点啊，准备开始啦！",
    "今天这是要发啊，哈哈!",
    "居然断线了，关键时刻掉链子",
    "扫雷不可怕，谁踩谁尴尬！",
    "哟嚯，你怎么又踩雷了！"];

var g_chatstr_nys = [
    "别吵了,别吵了,专心玩游戏",
    "君子报仇下局不晚,这局暂且放过你",
    "同志们,敢不敢火拼一把?",
    "我是庄家,谁敢挑战我?",
    "风水轮流转,这些钱全是我的",
    "哈哈哈,一把推注翻身了",
    "底牌搓出来绝对吓死你们",
    "这次是要牛气冲天啊，牛逼",
    "我加注了,你敢不敢跟?",
    "这样也被我赢了,真是服了",
    "看我通杀全场!",
    "我早就看穿你的牌了,哈哈!"];

var g_chatstr_bzw_man = [
    "兄弟们,敢不敢火拼一把",
    "我是庄家,谁敢挑战我",
    "试试今天的手气",
    "看我大杀四方",
    "君子爱财,取之有道",
    "唉,香油钱都输没了"
];

var g_chatstr_bzw_woman = [
    "姐妹们,敢不敢火拼一把",
    "我是庄家,谁敢挑战我",
    "试试我的手气如何",
    "看我大杀四方",
    "我是高高在上的女皇,呵呵呵呵",
    "唉,真是红颜薄命啊"
];




var g_face = [
    "res/ui/commonCells/commonPic/chatPic/chat_1.png",
    "res/ui/commonCells/commonPic/chatPic/chat_2.png",
    "res/ui/commonCells/commonPic/chatPic/chat_3.png",
    "res/ui/commonCells/commonPic/chatPic/chat_4.png",
    "res/ui/commonCells/commonPic/chatPic/chat_5.png",
    "res/ui/commonCells/commonPic/chatPic/chat_6.png",
    "res/ui/commonCells/commonPic/chatPic/chat_7.png",
    "res/ui/commonCells/commonPic/chatPic/chat_8.png",
    "res/ui/commonCells/commonPic/chatPic/chat_9.png",
    "res/ui/commonCells/commonPic/chatPic/chat_10.png",
    "res/ui/commonCells/commonPic/chatPic/chat_11.png",
    "res/ui/commonCells/commonPic/chatPic/chat_12.png",
    "res/ui/commonCells/commonPic/chatPic/chat_13.png",
    "res/ui/commonCells/commonPic/chatPic/chat_14.png",
    "res/ui/commonCells/commonPic/chatPic/chat_15.png",
    "res/ui/commonCells/commonPic/chatPic/chat_16.png",
    "res/ui/commonCells/commonPic/chatPic/chat_17.png",
    "res/ui/commonCells/commonPic/chatPic/chat_18.png",
    "res/ui/commonCells/commonPic/chatPic/chat_19.png",
    "res/ui/commonCells/commonPic/chatPic/chat_20.png",
];

for(var i = 0;i < g_face.length;i++){
    g_resources.push(g_face[i]);
}


var goldniu_music = {
    niu_100_w: "res/sound/dn_effect/niu_niu_w.mp3",
    niu_700_w: "res/sound/dn_effect/niu_sizha_w.mp3",
    niu_400_w: "res/sound/dn_effect/niu_wuhua_w.mp3",
    niu_500_w: "res/sound/dn_effect/niu_5_s_w.mp3",
};

var g_music = {
    bmg: "res/sound/bgplay.mp3",
    flychips:"res/sound/fly_effect/chips_fly.mp3",
    flycoins:"res/sound/fly_effect/coins_fly.mp3",
    selectGameMp3: "res/sound/selectGame.mp3",
    unselectMp3: "res/sound/unselect.mp3",
    selectItemMp3:"res/sound/selectItem.mp3",
    touchGrilMp3:"res/sound/touchGril.mp3",
    niu_0_w: "res/sound/dn_effect/niu_0_w.mp3",
    niu_91_w: "res/sound/dn_effect/niu_1_w.mp3",
    niu_92_w: "res/sound/dn_effect/niu_2_w.mp3",
    niu_93_w: "res/sound/dn_effect/niu_3_w.mp3",
    niu_94_w: "res/sound/dn_effect/niu_4_w.mp3",
    niu_95_w: "res/sound/dn_effect/niu_5_w.mp3",
    niu_96_w: "res/sound/dn_effect/niu_6_w.mp3",
    niu_97_w: "res/sound/dn_effect/niu_7_w.mp3",
    niu_98_w: "res/sound/dn_effect/niu_8_w.mp3",
    niu_99_w: "res/sound/dn_effect/niu_9_w.mp3",
    niu_100_w: "res/sound/dn_effect/niu_niu_w.mp3",
    niu_700_w: "res/sound/dn_effect/niu_sizha_w.mp3",
    niu_300_w: "res/sound/dn_effect/niu_wuhua_w.mp3",
    niu_500_w: "res/sound/dn_effect/niu_5_s_w.mp3",
    niu_0_m: "res/sound/dn_effect/niu_0_m.mp3",
    niu_91_m: "res/sound/dn_effect/niu_1_m.mp3",
    niu_92_m: "res/sound/dn_effect/niu_2_m.mp3",
    niu_93_m: "res/sound/dn_effect/niu_3_m.mp3",
    niu_94_m: "res/sound/dn_effect/niu_4_m.mp3",
    niu_95_m: "res/sound/dn_effect/niu_5_m.mp3",
    niu_96_m: "res/sound/dn_effect/niu_6_m.mp3",
    niu_97_m: "res/sound/dn_effect/niu_7_m.mp3",
    niu_98_m: "res/sound/dn_effect/niu_8_m.mp3",
    niu_99_m: "res/sound/dn_effect/niu_9_m.mp3",
    niu_100_m: "res/sound/dn_effect/niu_niu_m.mp3",
    niu_700_m: "res/sound/dn_effect/niu_sizha_m.mp3",
    niu_300_m: "res/sound/dn_effect/niu_wuhua_m.mp3",
    niu_500_m: "res/sound/dn_effect/niu_5_s_m.mp3",

    fix_msg_1: "res/sound/fix_msg_1.mp3",
    fix_msg_2: "res/sound/fix_msg_2.mp3",
    fix_msg_3: "res/sound/fix_msg_3.mp3",
    fix_msg_4: "res/sound/fix_msg_4.mp3",
    fix_msg_5: "res/sound/fix_msg_5.mp3",
    fix_msg_6: "res/sound/fix_msg_6.mp3",
    fix_msg_7: "res/sound/fix_msg_7.mp3",
    fix_msg_8: "res/sound/fix_msg_8.mp3",
    fix_msg_9: "res/sound/fix_msg_9.mp3",

    //龍珠多寶
    //dra_freezhuan:"res/sound/dragon/GoldenDragon_freespinbgm.mp3",
    //dra_dianzhuan:"res/sound/dragon/GoldenDragon_spin.mp3",
    //dra_zhuanstop:"res/sound/dragon/GoldenDragon_Reel_Stop.mp3",
    //dra_zhongjiang:"res/sound/dragon/GoldenDragon_win.mp3",
    //dra_getchip:"res/sound/dragon/Getchip.mp3",
    //dra_click:"res/sound/dragon/GoldenDragon_Click.mp3",
    //dra_wild:"res/sound/dragon/GoldenDragon_wild.mp3",
    //
    ////地穴探宝
    //dfh_walk:"res/sound/dxtb/dfh_walk.mp3",
    //dfh_deathdown:"res/sound/dxtb/dfh_deathdown.mp3",
    //dfh_deathup:"res/sound/dxtb/dfh_deathup.mp3",
    //dfh_zhuan:"res/sound/dxtb/dfh_zhuan.mp3",

    //斗地主音效
    Man_0: "res/sound/ddz_effect/Man_0.mp3",
    Man_1: "res/sound/ddz_effect/Man_1.mp3",
    Man_2: "res/sound/ddz_effect/Man_2.mp3",
    Man_3: "res/sound/ddz_effect/Man_3.mp3",
    Man_4: "res/sound/ddz_effect/Man_4.mp3",
    Man_5: "res/sound/ddz_effect/Man_5.mp3",
    Man_6: "res/sound/ddz_effect/Man_6.mp3",
    Man_7: "res/sound/ddz_effect/Man_7.mp3",
    Man_8: "res/sound/ddz_effect/Man_8.mp3",
    Man_9: "res/sound/ddz_effect/Man_9.mp3",
    Man_10: "res/sound/ddz_effect/Man_10.mp3",
    Man_11: "res/sound/ddz_effect/Man_11.mp3",
    Man_12: "res/sound/ddz_effect/Man_12.mp3",
    Man_13: "res/sound/ddz_effect/Man_13.mp3",
    Man_14: "res/sound/ddz_effect/Man_14.mp3",

    Man_dui0: "res/sound/ddz_effect/Man_dui0.mp3",
    Man_dui1: "res/sound/ddz_effect/Man_dui1.mp3",
    Man_dui2: "res/sound/ddz_effect/Man_dui2.mp3",
    Man_dui3: "res/sound/ddz_effect/Man_dui3.mp3",
    Man_dui4: "res/sound/ddz_effect/Man_dui4.mp3",
    Man_dui5: "res/sound/ddz_effect/Man_dui5.mp3",
    Man_dui6: "res/sound/ddz_effect/Man_dui6.mp3",
    Man_dui7: "res/sound/ddz_effect/Man_dui7.mp3",
    Man_dui8: "res/sound/ddz_effect/Man_dui8.mp3",
    Man_dui9: "res/sound/ddz_effect/Man_dui9.mp3",
    Man_dui10: "res/sound/ddz_effect/Man_dui10.mp3",
    Man_dui11: "res/sound/ddz_effect/Man_dui11.mp3",
    Man_dui12: "res/sound/ddz_effect/Man_dui12.mp3",

    Man_tuple0: "res/sound/ddz_effect/Man_tuple0.mp3",
    Man_tuple1: "res/sound/ddz_effect/Man_tuple1.mp3",
    Man_tuple2: "res/sound/ddz_effect/Man_tuple2.mp3",
    Man_tuple3: "res/sound/ddz_effect/Man_tuple3.mp3",
    Man_tuple4: "res/sound/ddz_effect/Man_tuple4.mp3",
    Man_tuple5: "res/sound/ddz_effect/Man_tuple5.mp3",
    Man_tuple6: "res/sound/ddz_effect/Man_tuple6.mp3",
    Man_tuple7: "res/sound/ddz_effect/Man_tuple7.mp3",
    Man_tuple8: "res/sound/ddz_effect/Man_tuple8.mp3",
    Man_tuple9: "res/sound/ddz_effect/Man_tuple9.mp3",
    Man_tuple10: "res/sound/ddz_effect/Man_tuple10.mp3",
    Man_tuple11: "res/sound/ddz_effect/Man_tuple11.mp3",
    Man_tuple12: "res/sound/ddz_effect/Man_tuple12.mp3",

    Man_zhadan: "res/sound/ddz_effect/Man_zhadan.mp3",
    Man_sandaiyi: "res/sound/ddz_effect/Man_sandaiyi.mp3",
    Man_sandaiyidui: "res/sound/ddz_effect/Man_sandaiyidui.mp3",
    Man_shunzi: "res/sound/ddz_effect/Man_shunzi.mp3",
    Man_liandui: "res/sound/ddz_effect/Man_liandui.mp3",
    Man_sidaier: "res/sound/ddz_effect/Man_sidaier.mp3",
    Man_sidailiangdui: "res/sound/ddz_effect/Man_sidailiangdui.mp3",
    Man_feiji: "res/sound/ddz_effect/Man_feiji.mp3",
    Man_wangzha: "res/sound/ddz_effect/Man_wangzha.mp3",
    Man_buyao: "res/sound/ddz_effect/Man_buyao.mp3",
    Man_NoOrder: "res/sound/ddz_effect/Man_NoOrder.mp3",
    Man_Order: "res/sound/ddz_effect/Man_Order.mp3",
    Man_Rob1: "res/sound/ddz_effect/Man_Rob1.mp3",
    Man_bujiabei: "res/sound/ddz_effect/Man_bujiabei.mp3",
    Man_jiabei: "res/sound/ddz_effect/Man_jiabei.mp3",
    Woman_jiabei:"res/sound/ddz_effect/Woman_jiabei.mp3",

    //炸金花
    f_add: "res/sound/zjh_effect/f_add.mp3",
    f_follow1: "res/sound/zjh_effect/f_follow1.mp3",
    f_giveup: "res/sound/zjh_effect/f_giveup.mp3",
    f_see: "res/sound/zjh_effect/f_see.mp3",
    fire: "res/sound/zjh_effect/fire.mp3",
    m_add: "res/sound/zjh_effect/m_add.mp3",
    m_follow1: "res/sound/zjh_effect/m_follow1.mp3",
    m_giveup: "res/sound/zjh_effect/m_giveup.mp3",
    m_see: "res/sound/zjh_effect/m_see.mp3",
    Man_one_card: "res/sound/ddz_effect/Man_one_card.mp3",
    Man_two_card: "res/sound/ddz_effect/Man_two_card.mp3",

    //炸金花金币场
    pleaseBet:"res/sound/zjh_effect/pleaseBet.mp3",
    zjhBg:"res/sound/zjh_effect/zjhBg.mp3",

    //赛马
    racingstart: "res/sound/saima/horse_start.mp3",
    racingrun: "res/sound/saima/horse_run_bgm.mp3",
    racingbets: "res/sound/saima/horse_bet_bg.mp3",
    racingwin: "res/sound/saima/horse_win.mp3",

    /*
    * 十点半
    * */
    sdb_boomCard  : "res/sound/sdb_effect/boomCard.mp3",
    sdb_dealCard  : "res/sound/sdb_effect/dealCard.mp3",
    sdb_dontCard  : "res/sound/sdb_effect/dontCard.mp3",
    sdb_double    : "res/sound/sdb_effect/double.mp3",
    sdb_fiveSmall : "res/sound/sdb_effect/fiveSmall.mp3",
    sdb_hwx       : "res/sound/sdb_effect/hwx.mp3",
    sdb_king      : "res/sound/sdb_effect/king.mp3",
    sdb_tallCard  : "res/sound/sdb_effect/tallCard.mp3",
    sdb_tenHalf   : "res/sound/sdb_effect/tenHalf.mp3",
    sdb_wantCard  : "res/sound/sdb_effect/wantCard.mp3",

    game_fapai : "res/sound/gamefapai.mp3",

    game_ptj_bet:"res/game/pingtianjiu/sound/bet.mp3",
    game_ptj_dealcard:"res/game/pingtianjiu/sound/dealcard.mp3",
    game_ptj_dice:"res/game/pingtianjiu/sound/dice.mp3",
    game_ptj_kaicard:"res/game/pingtianjiu/sound/kaicard.mp3",
    game_ptj_pleasebet:"res/game/pingtianjiu/sound/pleasebet.mp3",
    game_ptj_rocksezi:"res/game/pingtianjiu/sound/rockdice.mp3",

    gold_ring   : "res/sound/bet.mp3",
    sl_suc      : "res/sound/sl_suc.mp3",
    sl_msg_m1   : "res/sound/sl_effect/sl_msg_m1.mp3",
    sl_msg_m2   : "res/sound/sl_effect/sl_msg_m2.mp3",
    sl_msg_m3   : "res/sound/sl_effect/sl_msg_m3.mp3",
    sl_msg_m4   : "res/sound/sl_effect/sl_msg_m4.mp3",
    sl_msg_m5   : "res/sound/sl_effect/sl_msg_m5.mp3",
    sl_msg_m6   : "res/sound/sl_effect/sl_msg_m6.mp3",
    sl_msg_m7   : "res/sound/sl_effect/sl_msg_m7.mp3",
    sl_msg_m8   : "res/sound/sl_effect/sl_msg_m8.mp3",
    sl_msg_m9   : "res/sound/sl_effect/sl_msg_m9.mp3",
    sl_msg_w1   : "res/sound/sl_effect/sl_msg_w1.mp3",
    sl_msg_w2   : "res/sound/sl_effect/sl_msg_w2.mp3",
    sl_msg_w3   : "res/sound/sl_effect/sl_msg_w3.mp3",
    sl_msg_w4   : "res/sound/sl_effect/sl_msg_w4.mp3",
    sl_msg_w5   : "res/sound/sl_effect/sl_msg_w5.mp3",
    sl_msg_w6   : "res/sound/sl_effect/sl_msg_w6.mp3",
    sl_msg_w7   : "res/sound/sl_effect/sl_msg_w7.mp3",
    sl_msg_w8   : "res/sound/sl_effect/sl_msg_w8.mp3",
    sl_msg_w9   : "res/sound/sl_effect/sl_msg_w9.mp3",

    //卡五星
    //bmg: "res/sound/bgm.m4a",
    s1: "res/sound/kwx/1.mp3",
    s2: "res/sound/kwx/2.mp3",
    s3: "res/sound/kwx/3.mp3",
    s4: "res/sound/kwx/4.mp3",
    s5: "res/sound/kwx/5.mp3",
    s6: "res/sound/kwx/6.mp3",
    s7: "res/sound/kwx/7.mp3",
    s8: "res/sound/kwx/8.mp3",
    s9: "res/sound/kwx/9.mp3",
    s11: "res/sound/kwx/11.mp3",
    s12: "res/sound/kwx/12.mp3",
    s13: "res/sound/kwx/13.mp3",
    s14: "res/sound/kwx/14.mp3",
    s15: "res/sound/kwx/15.mp3",
    s16: "res/sound/kwx/16.mp3",
    s17: "res/sound/kwx/17.mp3",
    s18: "res/sound/kwx/18.mp3",
    s19: "res/sound/kwx/19.mp3",
    s31: "res/sound/kwx/31.mp3",
    s32: "res/sound/kwx/32.mp3",
    s33: "res/sound/kwx/33.mp3",
    peng: "res/sound/kwx/peng.mp3",
    gang: "res/sound/kwx/gang.mp3",
    liang: "res/sound/kwx/liang.mp3",
    hu: "res/sound/kwx/hu.mp3",
    zimo: "res/sound/kwx/zimo.mp3",
    //一夜暴富
    //yybfbgm: "res/sound/yybf/dscc40.mp3",
    //龙虎斗
    lhdresult0: "res/sound/lhd/longwin.mp3",
    lhdresult1: "res/sound/lhd/huwin.mp3",
    lhdresult2: "res/sound/lhd/he.mp3",
    lhdbgm: "res/sound/lhd/bgsound.mp3",
    lhdeffect1: "res/sound/lhd/lhdeff1.mp3",
    lhdeffect2: "res/sound/lhd/lhdeff2.mp3",
    lhdeffect3: "res/sound/lhd/lhdeff3.mp3",
    lhdeffect4: "res/sound/lhd/lhdeff4.mp3",
    lhdeffect5: "res/sound/lhd/lhdeff5.mp3",
    lhdeffect6: "res/sound/lhd/lhdeff6.mp3",
    lhdeffect7: "res/sound/lhd/lhdeff7.mp3",
    lhdeffect8: "res/sound/lhd/lhdeff8.mp3",
    lhdeffect9: "res/sound/lhd/lhdeff9.mp3",
    lhdeffect10: "res/sound/lhd/lhdeff10.mp3",
    lhdeffect11: "res/sound/lhd/lhdeff11.mp3",
    lhdeffect12: "res/sound/lhd/lhdeff12.mp3",
    lhdeffect13: "res/sound/lhd/lhdeff13.mp3",
    //豹子王
    //baozi:"res/sound/bzw/baozi.mp3",
    //dice2:"res/sound/bzw/dice2.mp3",
    //dice3:"res/sound/bzw/dice3.mp3",
    //dice4:"res/sound/bzw/dice4.mp3",
    //dice5:"res/sound/bzw/dice5.mp3",
    //dice6:"res/sound/bzw/dice6.mp3",
    //dice7:"res/sound/bzw/dice7.mp3",
    //dice8:"res/sound/bzw/dice8.mp3",
    //dice9:"res/sound/bzw/dice9.mp3",
    //dice10:"res/sound/bzw/dice10.mp3",
    //dice11:"res/sound/bzw/dice11.mp3",
    //dice12:"res/sound/bzw/dice12.mp3",
    //dice13:"res/sound/bzw/dice13.mp3",
    //dice14:"res/sound/bzw/dice14.mp3",
    //dice15:"res/sound/bzw/dice15.mp3",
    //dice16:"res/sound/bzw/dice16.mp3",
    //dice17:"res/sound/bzw/dice17.mp3",
    //baozi_dice3:"res/sound/bzw/baozi_dice3.mp3",
    //baozi_dice6:"res/sound/bzw/baozi_dice6.mp3",
    //baozi_dice9:"res/sound/bzw/baozi_dice9.mp3",
    //baozi_dice12:"res/sound/bzw/baozi_dice12.mp3",
    //baozi_dice15:"res/sound/bzw/baozi_dice15.mp3",
    //baozi_dice18:"res/sound/bzw/baozi_dice18.mp3",

    //! 翻牌机
    //fpjReward: "res/sound/fpj/S_Social_Reward.mp3",
    //fpjbem: "res/sound/fpj/Video_BGM.mp3",
    //fpjwinMuisc: "res/sound/fpj/Video_DoubleSuccess.mp3",
    //fpjsound1: "res/sound/fpj/Video_Voice1.mp3",
    //fpjsound2: "res/sound/fpj/Video_Voice2.mp3",
    //fpjsound3: "res/sound/fpj/Video_Voice3.mp3",
    //fpjsound4: "res/sound/fpj/Video_Voice4.mp3",
    //fpjsound5: "res/sound/fpj/Video_Voice5.mp3",
    //fpjsound6: "res/sound/fpj/Video_Voice6.mp3",
    //fpjsound7: "res/sound/fpj/Video_Voice7.mp3",
    //fpjsound8: "res/sound/fpj/Video_Voice8.mp3",
    //fpjsound9: "res/sound/fpj/Video_Voice9.mp3",

    //! 单双
    //diceds2:"res/sound/toubao/dice2.mp3",
    //diceds3:"res/sound/toubao/dice3.mp3",
    //diceds4:"res/sound/toubao/dice4.mp3",
    //diceds5:"res/sound/toubao/dice5.mp3",
    //diceds6:"res/sound/toubao/dice6.mp3",
    //diceds7:"res/sound/toubao/dice7.mp3",
    //diceds8:"res/sound/toubao/dice8.mp3",
    //diceds9:"res/sound/toubao/dice9.mp3",
    //diceds10:"res/sound/toubao/dice10.mp3",
    //diceds11:"res/sound/toubao/dice11.mp3",
    //diceds12:"res/sound/toubao/dice12.mp3",

    //kpTip:"res/sound/bzw/kpTip.mp3",
    //laugh0:"res/sound/bzw/laugh1.mp3",
    //laugh1:"res/sound/bzw/laugh2.mp3",
    //laugh2:"res/sound/bzw/laugh3.mp3",
    //lose0:"res/sound/bzw/lose1.mp3",
    //lose1:"res/sound/bzw/lose2.mp3",
    //openCup0:"res/sound/bzw/openCup0.mp3",
    openCup1:"res/sound/bzw/openCup1.mp3",
    //xzTip:"res/sound/bzw/xzTip.mp3",
    //ybao_bg:"res/sound/bzw/ybao_bg.mp3",
    //roll:"res/sound/bzw/roll.mp3",
    //xz0:"res/sound/bzw/xz1.mp3",
    //xz1:"res/sound/bzw/xz2.mp3",
    //xz2:"res/sound/bzw/xz3.mp3",
    //xz3:"res/sound/bzw/xz4.mp3",
    //xz4:"res/sound/bzw/xz5.mp3",
    //xz5:"res/sound/bzw/xz6.mp3",
    //xzds0:"res/sound/toubao/xz1.mp3",
    //xzds1:"res/sound/toubao/xz2.mp3",
    //xzds2:"res/sound/toubao/xz3.mp3",
    //xzds3:"res/sound/toubao/xz4.mp3",
    //xzds4:"res/sound/toubao/xz5.mp3",
    //xzds5:"res/sound/toubao/xz6.mp3",

    //ysz_dice3:"res/sound/bzw/ysz_dice3.mp3",
    //ysz_dice4:"res/sound/bzw/ysz_dice4.mp3",
    //ysz_dice5:"res/sound/bzw/ysz_dice5.mp3",
    //ysz_dice6:"res/sound/bzw/ysz_dice6.mp3",
    //ysz_dice7:"res/sound/bzw/ysz_dice7.mp3",
    //ysz_dice8:"res/sound/bzw/ysz_dice8.mp3",
    //ysz_dice9:"res/sound/bzw/ysz_dice9.mp3",
    //ysz_dice10:"res/sound/bzw/ysz_dice10.mp3",
    //ysz_dice11:"res/sound/bzw/ysz_dice11.mp3",
    //ysz_baozi_dice2:"res/sound/bzw/ysz_baozi_dice2.mp3",
    //ysz_baozi_dice4:"res/sound/bzw/ysz_baozi_dice4.mp3",
    //ysz_baozi_dice6:"res/sound/bzw/ysz_baozi_dice6.mp3",
    //ysz_baozi_dice8:"res/sound/bzw/ysz_baozi_dice8.mp3",
    //ysz_baozi_dice10:"res/sound/bzw/ysz_baozi_dice10.mp3",
    //ysz_baozi_dice12:"res/sound/bzw/ysz_baozi_dice12.mp3",
    ysz_kpTip:"res/sound/bzw/ysz_kpTip.mp3",
    ysz_laugh0:"res/sound/bzw/ysz_laugh1.mp3",
    ysz_laugh1:"res/sound/bzw/ysz_laugh2.mp3",
    ysz_laugh2:"res/sound/bzw/ysz_laugh3.mp3",
    ysz_lose0:"res/sound/bzw/ysz_lose1.mp3",
    ysz_lose1:"res/sound/bzw/ysz_lose2.mp3",
    ysz_xzTip:"res/sound/bzw/ysz_xzTip.mp3",
    ysz_xz0:"res/sound/bzw/ysz_xz1.mp3",
    ysz_xz1:"res/sound/bzw/ysz_xz2.mp3",
    ysz_xz2:"res/sound/bzw/ysz_xz3.mp3",
    ysz_xz3:"res/sound/bzw/ysz_xz4.mp3",
    ysz_xz4:"res/sound/bzw/ysz_xz5.mp3",
    ysz_xz5:"res/sound/bzw/ysz_xz6.mp3",

    winMusic:"res/sound/win.mp3",
    loseMusic:"res/sound/lose.mp3",

    //百人推筒子
    brttz_endsound1:"res/sound/brttz/ttz_tongsha.mp3",
    brttz_endsound2:"res/sound/brttz/ttz_tongpei.mp3",
    brttz_opencard:"res/sound/brttz/ttz_card_open.mp3",
    brttz_mdls:"res/sound/brttz/ttz_mdls.mp3",
    brttz_xz0:"res/sound/brttz/ttz_xz1.mp3",
    brttz_xz1:"res/sound/brttz/ttz_xz2.mp3",
    brttz_xz2:"res/sound/brttz/ttz_xz3.mp3",
    brttz_xz3:"res/sound/brttz/ttz_xz4.mp3",
    brttz_xz4:"res/sound/brttz/ttz_xz5.mp3",
    brttz_xz5:"res/sound/brttz/ttz_xz6.mp3",
    brttz_xz6:"res/sound/brttz/ttz_xz7.mp3",
    brttz_xztip:"res/sound/brttz/ttz_xz_tip.mp3",
    brttz_laugh0:"res/sound/brttz/ttz_xj_win.mp3",
    brttz_laugh1:"res/sound/brttz/ttz_xj_win_2.mp3",
    brttz_lose:"res/sound/brttz/ttz_xj_lose.mp3",
    brttz_bg:"res/sound/brttz/ttz_bg.mp3",

    //魔法表情
    magic0:"res/sound/magic_effect/maginc0.mp3",
    magic1:"res/sound/magic_effect/maginc1.mp3",
    magic2:"res/sound/magic_effect/maginc2.mp3",
    magic3:"res/sound/magic_effect/maginc3.mp3",
    magic4:"res/sound/magic_effect/maginc4.mp3",

    //跑得快
    buyao0:"res/sound/pdk/pdk_buyao.mp3",
    buyao1:"res/sound/pdk/pdk_guo.mp3",
    buyao2:"res/sound/pdk/pdk_yaobuqi.mp3",

    //神仙夺宝
    //sxdb_startRun:"res/sound/sxdb_music/sgj_start.mp3",
    //sxdb_loopRun:"res/sound/sxdb_music/sgj_loop.mp3",
    //sxdb_endRun:"res/sound/sxdb_music/sgj_end.mp3",
    //nansound_21:"res/sound/sxdb_music/nansound_21.mp3",
    //nansound_22:"res/sound/sxdb_music/nansound_22.mp3",
    //nansound_23:"res/sound/sxdb_music/nansound_23.mp3",
    //nansound_24:"res/sound/sxdb_music/nansound_24.mp3",
    //nansound_25:"res/sound/sxdb_music/nansound_25.mp3",
    //nansound_26:"res/sound/sxdb_music/nansound_26.mp3",
    //nansound_27:"res/sound/sxdb_music/nansound_27.mp3",
    //nansound_28:"res/sound/sxdb_music/nansound_28.mp3",
    //nansound_29:"res/sound/sxdb_music/nansound_29.mp3",

    //nvsound_11:"res/sound/sxdb_music/nvsound_11.mp3",
    //nvsound_12:"res/sound/sxdb_music/nvsound_12.mp3",
    //nvsound_13:"res/sound/sxdb_music/nvsound_13.mp3",
    //nvsound_14:"res/sound/sxdb_music/nvsound_14.mp3",
    //nvsound_15:"res/sound/sxdb_music/nvsound_15.mp3",
    //nvsound_16:"res/sound/sxdb_music/nvsound_16.mp3",
    //nvsound_17:"res/sound/sxdb_music/nvsound_17.mp3",
    //nvsound_18:"res/sound/sxdb_music/nvsound_18.mp3",
    //nvsound_19:"res/sound/sxdb_music/nvsound_19.mp3",
};

//扎金花金币场
for(var i = 0;i<4;i++){
    //跟牌
    g_music["m_g" + i] = "res/sound/zjh_effect/male/m_g" + i + ".mp3";
    g_music["f_g" + i] = "res/sound/zjh_effect/famale/f_g" + i + ".mp3";
    //加注
    g_music["m_j" + i] = "res/sound/zjh_effect/male/m_j" + i + ".mp3";
    g_music["f_j" + i] = "res/sound/zjh_effect/famale/f_j" + i + ".mp3";
    //弃牌
    g_music["m_q" + i] = "res/sound/zjh_effect/male/m_q" + i + ".mp3";
    g_music["f_q" + i] = "res/sound/zjh_effect/famale/f_q" + i + ".mp3";
    //看牌
    if(i < 2){
        g_music["m_k" + i] = "res/sound/zjh_effect/male/m_k" + i + ".mp3";
        g_music["f_k" + i] = "res/sound/zjh_effect/famale/f_k" + i + ".mp3";
    }
    //搓牌、比牌
    if(i < 1){
        g_music["m_c" + i] = "res/sound/zjh_effect/male/m_c" + i + ".mp3";
        g_music["f_c" + i] = "res/sound/zjh_effect/famale/f_c" + i + ".mp3";
        g_music["m_b" + i] = "res/sound/zjh_effect/male/m_b" + i + ".mp3";
        g_music["f_b" + i] = "res/sound/zjh_effect/famale/f_b" + i + ".mp3";
        g_music["f_b" + i] = "res/sound/zjh_effect/famale/f_b" + i + ".mp3";
    }
}

//豹子王
for(var i = 1;i < 7;i++ ){
    g_music["nan"+i] = "res/sound/bzw/nan"+i+".mp3";
    g_music["nv"+i] = "res/sound/bzw/nv"+i+".mp3";
}

var resnameman = []; resnameman[0] = 0;
var resnamewoman = []; resnamewoman[0] = 0;
for(var i = 1; i < 78; i++){
    resnameman[i] = "res/game/pingtianjiu/sound/man/"+ i+".mp3";
    resnamewoman[i] = "res/game/pingtianjiu/sound/woman/"+ i+".mp3";
    g_resources.push(resnameman[i]);
    g_resources.push(resnamewoman[i]);
};
//推筒子
g_music.ttzdealsd = "res/sound/ttz/TTZ_deal.mp3";
g_resources.push(g_music.ttzdealsd);
for(var k=0;k<24;k++){
    var ttzindex = 100+k*5; //方便了程序，但不方便阅读修改
    g_music["ttz_mansd_"+ttzindex] = "res/sound/ttz/man/ttz_mansd_"+k+".mp3";
    g_music["ttz_womansd_"+ttzindex] = "res/sound/ttz/woman/ttz_womansd_"+k+".mp3";
}
for (var i in g_music) {
    g_resources.push(g_music[i]);
}
for(var i in goldniu_music){
    g_resources.push(goldniu_music[i]);
}


var g_manTalk = [
    "res/sound/PT_M_quyu_0.mp3",
    "res/sound/PT_M_quyu_1.mp3",
    "res/sound/PT_M_quyu_2.mp3",
    "res/sound/PT_M_quyu_3.mp3",
    "res/sound/PT_M_quyu_4.mp3",
    "res/sound/PT_M_quyu_5.mp3",
    "res/sound/PT_M_quyu_6.mp3",
    "res/sound/PT_M_quyu_7.mp3",
    "res/sound/PT_M_quyu_8.mp3",
];


var g_womanTalk = [
    "res/sound/PT_W_quyu_0.mp3",
    "res/sound/PT_W_quyu_1.mp3",
    "res/sound/PT_W_quyu_2.mp3",
    "res/sound/PT_W_quyu_3.mp3",
    "res/sound/PT_W_quyu_4.mp3",
    "res/sound/PT_W_quyu_5.mp3",
    "res/sound/PT_W_quyu_6.mp3",
    "res/sound/PT_W_quyu_7.mp3",
    "res/sound/PT_W_quyu_8.mp3",
];

var nys_manTalk = []; nys_manTalk[0] = 0;
var nys_womanTalk = []; nys_womanTalk[0] = 0
for(var i = 0;i < 12;i++){
    nys_manTalk[i] = ("res/sound/nys_effect/nan/"+(i+1)+".mp3");
    nys_womanTalk[i] = ("res/sound/nys_effect/nv/"+(i+1)+".mp3");
    g_resources.push(nys_manTalk[i]);
    g_resources.push(nys_womanTalk[i]);
}


var g_magic_chat = {
    magic_chat_1_1_json: "res/btnAnimate/renjidan/renjidan1.json",
    magic_chat_1_1_atlas: "res/btnAnimate/renjidan/renjidan1.atlas",
    magic_chat_1_1_png: "res/btnAnimate/renjidan/renjidan1.png",
    magic_chat_1_2_json: "res/btnAnimate/renjidan/renjidan2.json",
    magic_chat_1_2_atlas: "res/btnAnimate/renjidan/renjidan2.atlas",
    magic_chat_1_2_png: "res/btnAnimate/renjidan/renjidan2.png",
    magic_chat_2_1_json: "res/btnAnimate/tuoxie/tuoxie1.json",
    magic_chat_2_1_atlas: "res/btnAnimate/tuoxie/tuoxie1.atlas",
    magic_chat_2_1_png: "res/btnAnimate/tuoxie/tuoxie1.png",
    magic_chat_2_2_json: "res/btnAnimate/tuoxie/tuoxie2.json",
    magic_chat_2_2_atlas: "res/btnAnimate/tuoxie/tuoxie2.atlas",
    magic_chat_2_2_png: "res/btnAnimate/tuoxie/tuoxie2.png",
    magic_chat_3_1_json: "res/btnAnimate/dianzan/dianzan1.json",
    magic_chat_3_1_atlas: "res/btnAnimate/dianzan/dianzan1.atlas",
    magic_chat_3_1_png: "res/btnAnimate/dianzan/dianzan1.png",
    magic_chat_3_2_json: "res/btnAnimate/dianzan/dianzan2.json",
    magic_chat_3_2_atlas: "res/btnAnimate/dianzan/dianzan2.atlas",
    magic_chat_3_2_png: "res/btnAnimate/dianzan/dianzan2.png",
    magic_chat_4_1_json: "res/btnAnimate/xianwen/xianwen1.json",
    magic_chat_4_1_atlas: "res/btnAnimate/xianwen/xianwen1.atlas",
    magic_chat_4_1_png: "res/btnAnimate/xianwen/xianwen1.png",
    magic_chat_4_2_json: "res/btnAnimate/xianwen/xianwen2.json",
    magic_chat_4_2_atlas: "res/btnAnimate/xianwen/xianwen2.atlas",
    magic_chat_4_2_png: "res/btnAnimate/xianwen/xianwen2.png",
    magic_chat_5_1_json: "res/btnAnimate/xianhua/xianhua1.json",
    magic_chat_5_1_atlas: "res/btnAnimate/xianhua/xianhua1.atlas",
    magic_chat_5_1_png: "res/btnAnimate/xianhua/xianhua1.png",
    magic_chat_5_2_json: "res/btnAnimate/xianhua/xianhua2.json",
    magic_chat_5_2_atlas: "res/btnAnimate/xianhua/xianhua2.atlas",
    magic_chat_5_2_png: "res/btnAnimate/xianhua/xianhua2.png",

};

for (var i in g_magic_chat) {
    g_resources.push(g_magic_chat[i]);
}
for(var i in g_womanTalk){
    g_resources.push(g_womanTalk[i]);
}

for(var i in g_manTalk){
    g_resources.push(g_manTalk[i]);
}